Domain owner + PCA + Policy Log
netsec-ethz/fpki pull request #3
Opened 2022-04-21 14:21 UTC by xuyongzhe-vt

Finished:
- Domain owner: Generate and send RCSR
- PCA: Issue RPC, send RPC to policy log
- Policy log: log RPC and generate SPT

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/fpki/3)

2022-04-21 17:09 UTC, XuYongzhe-ethz commented
Thank you so much for your feedback!
I change the files according to your feedback.

Some issues:
- It seems every pkg needs a go.mod. For example, `"common"` pkg needs a go.mod, although the go.mod is empty. Otherwise the compiler will complains. Maybe I made some mistakes. There is only one "valid" go.mod in the root. Rest of them are empty.
- I name the test file like `"test_crypto"` or `"test_json"`. Maybe it looks more clear, since the files start with the same letter will be ordered in the same block...I don't know it's a good practice, if you think it's messy, I can rename them later.

Change:
- I update the README, and it mentions how to run the code. If there is any issue, feel free to contact me!

2022-04-25 22:13 UTC, XuYongzhe-ethz commented
Hi Juan,

I made several changes according to your comments. There are two integration tests which will need the help of other processes(Trillian servers). I update the README, and it records the steps to set up the testing environment. All the unit tests will not need any other process. 

For the error types, I'm a little confused. Maybe we can discuss this in Thursday. 

And in the api folder, I create a file which introduces all the public functions in pdf. 

Please let me know if you have further comments. Thanks again for your feedback!

2022-04-28 08:41 UTC, juagargi commented
Interim I've run the following:
- `go mod tidy`
- `go fmt ./...`
I'll add these steps also in CI once we step it up.





<!-- Sent from Reviewable.io -->

2022-04-28 08:44 UTC, juagargi commented
You have added again `.DS_Store` :sweat_smile: 
Note: everytime that you do
`git add something/`
instead do 
`git add -u something/`
to avoid adding _new_ files. This will only update tracked ones.
Also every time you want to `git commit`, do a `git status` before. Ensure that what you are adding/changing is expected.





<!-- Sent from Reviewable.io -->

2022-04-28 08:47 UTC, juagargi commented
*[`docs/NewDesignFinal.pdf` line 0 at r11](https://reviewable.io/reviews/netsec-ethz/fpki/3#-N0W0Kcm1-XLNSZD-TpY:-N0W0KcnAF72HZj7wWSp:bplbu3o) ([raw file](https://github.com/netsec-ethz/fpki/blob/7994b3f286845f3c8b764ac19fbd9f1fdec6ffcd/docs/NewDesignFinal.pdf#L0)):*
In general don't commit binary files (PDFs are considered binary files), with the exception of a few images, etc.
We can leave it here for now.


<!-- Sent from Reviewable.io -->

2022-04-28 08:52 UTC, juagargi commented
Re. the error wrapping: please read https://golangbyexample.com/wrapping-and-unwrapping-error-golang/





<!-- Sent from Reviewable.io -->

2022-04-28 09:03 UTC, juagargi commented
Remind me to give you a quick tour on how to answer Reviewable comments. E.g. there are still a number of comments open on the `README.md` file.





<!-- Sent from Reviewable.io -->

2022-04-28 09:20 UTC, juagargi commented
*[`pkg/common/cert_test.go` line 8 at r18](https://reviewable.io/reviews/netsec-ethz/fpki/3#-N0jSu4b8AzbZ-DqBSOr:-N0jSu4b8AzbZ-DqBSOs:b-2n2hd4) ([raw file](https://github.com/netsec-ethz/fpki/blob/d76210f9ce53a281b7527d6bf569f2e686ab159f/pkg/common/cert_test.go#L8)):*
> ```Go
> 	"testing"
> 
> 	"github.com/stretchr/testify/require"
> ```

PTAL at how `testify` is used here and migrate all our tests to make use of it.


<!-- Sent from Reviewable.io -->

2022-04-28 15:40 UTC, juagargi requested changes
> Reviewed 40 of 172 files at r3, 44 of 122 files at r6, 20 of 81 files at r9, 33 of 34 files at r11, 27 of 56 files at r12, 1 of 1 files at r13, 1 of 2 files at r14, 4 of 4 files at r15, 1 of 1 files at r16, 3 of 5 files at r18, 1 of 4 files at r19, 4 of 8 files at r22, 2 of 3 files at r23, 2 of 2 files at r24.
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/fpki/3)* status: 176 of 202 files reviewed, 66 unresolved discussions / 0 of 1 LGTMs obtained / 0 of 1 approvals obtained

___
*[`cmd/config/logserver_config` line 1 at r16](https://reviewable.io/reviews/netsec-ethz/fpki/3#-N0jPd3M00QlR5U5lZkn:-N0jPd3M00QlR5U5lZko:bxalc9w) ([raw file](https://github.com/netsec-ethz/fpki/blob/b9eb453e04c289169956efede62ed5a72f6107dd/cmd/config/logserver_config#L1)):*
> ```
> {
> ```

this looks like a JSON file. Shouldn't it be named `logserver_config.json`?
And be located under `cmd/logserver` ?
___
*[`cmd/config/logsigner_config` line 1 at r16](https://reviewable.io/reviews/netsec-ethz/fpki/3#-N0jPxSJ4vMDH6-Of2jM:-N0jPxSJ4vMDH6-Of2jN:b-k32dk5) ([raw file](https://github.com/netsec-ethz/fpki/blob/b9eb453e04c289169956efede62ed5a72f6107dd/cmd/config/logsigner_config#L1)):*
> ```
> {
> ```

same as before, this is a json file and should be under `cmd/logsigner`
___
*[`pkg/common/cert.go` line 29 at r11](https://reviewable.io/reviews/netsec-ethz/fpki/3#-N0W1aup6ztTULs5QCSh:-N0W1aup6ztTULs5QCSi:b1p2zia) ([raw file](https://github.com/netsec-ethz/fpki/blob/7994b3f286845f3c8b764ac19fbd9f1fdec6ffcd/pkg/common/cert.go#L29)):*
> ```Go
>     )
> 
>     return pubkey_pem, nil
> ```

it's more go friendly to do:
```go
    return pem.EncodeToMemory(
        &pem.Block{
            Type:  "RSA PUBLIC KEY",
            Bytes: pubkey_bytes,
        },
    ), nil
```
___
*[`pkg/common/cert.go` line 20 at r16](https://reviewable.io/reviews/netsec-ethz/fpki/3#-N0jN4oI688df6Qmyaq3:-N0jN4oI688df6Qmyaq4:bktpen0) ([raw file](https://github.com/netsec-ethz/fpki/blob/b9eb453e04c289169956efede62ed5a72f6107dd/pkg/common/cert.go#L20)):*
> ```Go
> 	pubkey_bytes, err := x509.MarshalPKIXPublicKey(pubkey)
> 	if err != nil {
> 		return []byte{}, fmt.Errorf("RsaPublicKeyToPemBytes | MarshalPKIXPublicKey | %s", err.Error())
> ```

wrap errors this way: (note the `%w`)
```go
return []byte{}, fmt.Errorf("RsaPublicKeyToPemBytes | MarshalPKIXPublicKey | %w", err)
```
___
*[`pkg/common/cert.go` line 45 at r16](https://reviewable.io/reviews/netsec-ethz/fpki/3#-N0jLrgT7fi0M6EVBnQC:-N0jLrgT7fi0M6EVBnQD:b-4uc8yw) ([raw file](https://github.com/netsec-ethz/fpki/blob/b9eb453e04c289169956efede62ed5a72f6107dd/pkg/common/cert.go#L45)):*
> ```Go
> 
> 	switch pub := pub.(type) {
> 	case *rsa.PublicKey:
> ```

do a type assertion instead of an only one case switch:
```go
if rsaPub, ok := pub.(*rsa.PublicKey); ok {
	return rsaPub, nil
}
return nil, errors.New("PemBytesToRsaPublicKey | ParsePKIXPublicKey | Key type is not RSA")
```
___
*[`pkg/common/cert.go` line 48 at r16](https://reviewable.io/reviews/netsec-ethz/fpki/3#-N0jLh0t60lfVHmzgYF2:-N0jLh0t60lfVHmzgYF3:b3s1oek) ([raw file](https://github.com/netsec-ethz/fpki/blob/b9eb453e04c289169956efede62ed5a72f6107dd/pkg/common/cert.go#L48)):*
> ```Go
> 		return pub, nil
> 	default:
> 		break
> ```

remove. No need for a `default` that does nothing.



_Code quote:_
```Go
	default:
		break
```
___
*[`pkg/common/cert.go` line 70 at r16](https://reviewable.io/reviews/netsec-ethz/fpki/3#-N0jNi8KAPWaOlKvvuyL:-N0jNi8KAPWaOlKvvuyM:b-x81mf4) ([raw file](https://github.com/netsec-ethz/fpki/blob/b9eb453e04c289169956efede62ed5a72f6107dd/pkg/common/cert.go#L70)):*
> ```Go
> 	if block.Type != "CERTIFICATE" {
> 		return nil, fmt.Errorf("X509CertFromFile | %s contains data other than certificate", fileName)
> 	}
> ```

In Go, switches are like a collection of `if` conditions. it's more readable to do:
```go
switch{
case block==nil:
	return nil, fmt.Errorf("X509CertFromFile | no pem block in %s", fileName)
case block.Type == "CERTIFICATE":
	return nil, fmt.Errorf("X509CertFromFile | %s contains data other than certificate", fileName)
}
```



_Code quote:_
```Go
	if block == nil {
		return nil, fmt.Errorf("X509CertFromFile | no pem block in %s", fileName)
	}

	if block.Type != "CERTIFICATE" {
		return nil, fmt.Errorf("X509CertFromFile | %s contains data other than certificate", fileName)
	}
```
___
*[`pkg/common/crypto.go` line 13 at r16](https://reviewable.io/reviews/netsec-ethz/fpki/3#-N0kPv5X76tzN5EfuxlC:-N0kPv5X76tzN5EfuxlD:b-26rlbp) ([raw file](https://github.com/netsec-ethz/fpki/blob/b9eb453e04c289169956efede62ed5a72f6107dd/pkg/common/crypto.go#L13)):*
> ```Go
> )
> 
> // currently only SHA256 and RSA is supported
> ```

all public types should start their comments with the name of the type, function, etc.
___
*[`pkg/common/crypto.go` line 23 at r16](https://reviewable.io/reviews/netsec-ethz/fpki/3#-N0kPQMb873aKWHYpgsk:-N0kPQMb873aKWHYpgsl:b-479j9m) ([raw file](https://github.com/netsec-ethz/fpki/blob/b9eb453e04c289169956efede62ed5a72f6107dd/pkg/common/crypto.go#L23)):*
> ```Go
> 
> const (
> 	RSA PublicKeyAlgorithm = iota
> ```

move the constants all together (below `SHA256`)
___
*[`pkg/common/crypto.go` line 55 at r16](https://reviewable.io/reviews/netsec-ethz/fpki/3#-N0kPm1V-Jm-cTiItKOg:-N0kPm1V-Jm-cTiItKOh:bmkuwfu) ([raw file](https://github.com/netsec-ethz/fpki/blob/b9eb453e04c289169956efede62ed5a72f6107dd/pkg/common/crypto.go#L55)):*
> ```Go
> // Generate a signature, and fill the signature in the RCSR
> func RCSRCreateSignature(domainOwnerPrivKey *rsa.PrivateKey, rcsr *RCSR) error {
> 	// clear signature; normally should be
> ```

I don't understand the comment
___
*[`pkg/common/crypto.go` line 90 at r16](https://reviewable.io/reviews/netsec-ethz/fpki/3#-N0kQXCTCPsMzGkQKzVZ:-N0kQXCTCPsMzGkQKzV_:bpsu9ac) ([raw file](https://github.com/netsec-ethz/fpki/blob/b9eb453e04c289169956efede62ed5a72f6107dd/pkg/common/crypto.go#L90)):*
> ```Go
> 		TimeStamp:          rcsr.TimeStamp,
> 		PublicKeyAlgorithm: rcsr.PublicKeyAlgorithm,
> 		PublicKey:          rcsr.PublicKey,
> ```

this is not a deep copy
___
*[`pkg/common/crypto.go` line 96 at r16](https://reviewable.io/reviews/netsec-ethz/fpki/3#-N0kQnJW2w4IpFd286JV:-N0kQnJW2w4IpFd286JW:byu9omf) ([raw file](https://github.com/netsec-ethz/fpki/blob/b9eb453e04c289169956efede62ed5a72f6107dd/pkg/common/crypto.go#L96)):*
> ```Go
> 	}
> 
> 	serialisedStruc, err := JsonStrucToBytes(rcsrCopy)
> ```

it seems you don't need a deep copy anyways. Same for the other places in this file where you use deep copy.
___
*[`pkg/common/crypto.go` line 209 at r16](https://reviewable.io/reviews/netsec-ethz/fpki/3#-N0kR8wk0UGkZneW8Kpm:-N0kR8wk0UGkZneW8Kpn:b-j9xu9p) ([raw file](https://github.com/netsec-ethz/fpki/blob/b9eb453e04c289169956efede62ed5a72f6107dd/pkg/common/crypto.go#L209)):*
> ```Go
> 
> 	// if every thing is correct, the err will be nil
> 	return err
> ```

```go
return rsa.VerifyPKCS1v15(pubKey, crypto.SHA256, hashOutput[:], rpc.CASignature)
```



_Code quote:_
```Go
	err = rsa.VerifyPKCS1v15(pubKey, crypto.SHA256, hashOutput[:], rpc.CASignature)

	// if every thing is correct, the err will be nil
	return err
```
___
*[`pkg/common/json.go` line 13 at r16](https://reviewable.io/reviews/netsec-ethz/fpki/3#-N0kIPjw4auWRXVGjklx:-N0kIPjw4auWRXVGjkly:biw4hmw) ([raw file](https://github.com/netsec-ethz/fpki/blob/b9eb453e04c289169956efede62ed5a72f6107dd/pkg/common/json.go#L13)):*
> ```Go
> 
> // marshall structure to bytes, and store them in a file
> func JsonStrucToFile(struc interface{}, filePath string) error {
> ```

remember to start the comments of all public functions with the name of the function
___
*[`pkg/common/json.go` line 43 at r16](https://reviewable.io/reviews/netsec-ethz/fpki/3#-N0kOB6AD-BVOCa2KqvO:-N0kOB6AD-BVOCa2KqvP:b6xtumt) ([raw file](https://github.com/netsec-ethz/fpki/blob/b9eb453e04c289169956efede62ed5a72f6107dd/pkg/common/json.go#L43)):*
> ```Go
> 	default:
> 		return nil, fmt.Errorf("Structure not supported yet! [...]

2022-05-04 15:44 UTC, juagargi requested changes
> Reviewed 3 of 55 files at r26, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/fpki/3)* status: 153 of 217 files reviewed, 72 unresolved discussions / 0 of 1 LGTMs obtained / 0 of 1 approvals obtained

___
*[`Makefile` line 15 at r26](https://reviewable.io/reviews/netsec-ethz/fpki/3#-N1EfclZ8nfuYDxY_Z8z:-N1Efcl_9QRVb-Yax3Ou:b-vjyei3) ([raw file](https://github.com/netsec-ethz/fpki/blob/a0d24cb3b1cdaa6c40e4a87329fe6207f998fff2/Makefile#L15)):*
> ```Makefile
> 	@rm -f tests/intergration_tests/domainowner_pca_policlog_interaction/file_exchange/policylog/trees_config/*
> 	@rm -f tests/intergration_tests/domainowner_pca_policlog_interaction/file_exchange/pcaoutput/rpc/*
> 	@rm -f pkg/common/testdata/*.json
> ```

Data inside `testdata` is intended to be used by the unit tests.
Unit tests can write data to a temporary directory, not to `testdata`.
Please look at e.g. map_test.go and find a line like this
```go
tempFile := path.Join(os.TempDir(), "root")
```
for inspiration.
___
*[`Makefile` line 17 at r26](https://reviewable.io/reviews/netsec-ethz/fpki/3#-N1Eg8Ik1PP3nk9WmBK_:-N1Eg8Il-zh5MKIeKUuh:b-gzlwho) ([raw file](https://github.com/netsec-ethz/fpki/blob/a0d24cb3b1cdaa6c40e4a87329fe6207f998fff2/Makefile#L17)):*
> ```Makefile
> 	@rm -f pkg/common/testdata/*.json
> 	@rm -r tests/intergration_tests/performance_test/testdata/trees_config
> 	@find . -name ".DS_Store" -delete
> ```

Remove this.
No files `.DS_Store` should be committed, but there should not exist a rule to remove them from the filesystem.
___
*[`Makefile` line 18 at r26](https://reviewable.io/reviews/netsec-ethz/fpki/3#-N1EgOibAG4I5fK-Veqi:-N1EgOibAG4I5fK-Veqj:b7sdgtu) ([raw file](https://github.com/netsec-ethz/fpki/blob/a0d24cb3b1cdaa6c40e4a87329fe6207f998fff2/Makefile#L18)):*
> ```Makefile
> 	@rm -r tests/intergration_tests/performance_test/testdata/trees_config
> 	@find . -name ".DS_Store" -delete
> 	@rm -f pkg/policylog/server/logserver/logserver_config.json
> ```

this file shouldn't be here. Ensure the config_test doesn't create it in the first place (use a temporary file for that instead)
___
*[`Makefile` line 23 at r26](https://reviewable.io/reviews/netsec-ethz/fpki/3#-N1Ei9i53jk82UWnS-9g:-N1EgkKS8U0YSMtLKkH6:b-iptdey) ([raw file](https://github.com/netsec-ethz/fpki/blob/a0d24cb3b1cdaa6c40e4a87329fe6207f998fff2/Makefile#L23)):*
> ```Makefile
> 	@go build -o bin/logserver_exec cmd/logserver/logserver_exec.go
> 	@go build -o bin/logsigner_exec cmd/logsigner/logsigner_exec.go
> 	@cp config/logserver_config.json bin/logserver_config.json
> ```

The plan is to have `bin` with the binaries. The configuration can live somewhere else.
Have the binaries accept a parameter with the location of the config file.
___
*[`Makefile` line 34 at r26](https://reviewable.io/reviews/netsec-ethz/fpki/3#-N1EiO3W37xiIrP_q1kb:-N1EiO3W37xiIrP_q1kc:bb7phvt) ([raw file](https://github.com/netsec-ethz/fpki/blob/a0d24cb3b1cdaa6c40e4a87329fe6207f998fff2/Makefile#L34)):*
> ```Makefile
> 	@mkdir -p tests/intergration_tests/performance_test/testdata/trees_config/
> 
> cerate_database:
> ```

typo
___
*[`Makefile` line 39 at r26](https://reviewable.io/reviews/netsec-ethz/fpki/3#-N1EiTL8CbN5JFV6lAZx:-N1EiTL8CbN5JFV6lAZy:ba4ys05) ([raw file](https://github.com/netsec-ethz/fpki/blob/a0d24cb3b1cdaa6c40e4a87329fe6207f998fff2/Makefile#L39)):*
> ```Makefile
> reset_tables:
> 	@mysql -u root -e "DROP TABLE map.node;"
> 	@mysql -u root -e "DROP TABLE map.value;"
> ```

add an empty line at the end.
___
*[`go.mod` line 21 at r26](https://reviewable.io/reviews/netsec-ethz/fpki/3#-N1EhkrX3VL90ziKtVKl:-N1EhkrX3VL90ziKtVKm:b8uhq7s) ([raw file](https://github.com/netsec-ethz/fpki/blob/a0d24cb3b1cdaa6c40e4a87329fe6207f998fff2/go.mod#L21)):*
> ```XML
> )
> 
> require (
> ```

you have added back the `require` that I had removed.


<!-- Sent from Reviewable.io -->

2022-05-04 15:48 UTC, XuYongzhe-ethz reviewed
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/fpki/3)* status: 153 of 217 files reviewed, 72 unresolved discussions / 0 of 1 LGTMs obtained / 0 of 1 approvals obtained

___
*[`pkg/common/cert.go` line 29 at r11](https://reviewable.io/reviews/netsec-ethz/fpki/3#-N0W1aup6ztTULs5QCSh:-N0vjOr-6B9po6-RAwUm:b-896fix) ([raw file](https://github.com/netsec-ethz/fpki/blob/7994b3f286845f3c8b764ac19fbd9f1fdec6ffcd/pkg/common/cert.go#L29)):*
<details><summary><i>Previously, juagargi (Juan A. Garcia Pardo) wrote…</i></summary><blockquote>

it's more go friendly to do:
```go
    return pem.EncodeToMemory(
        &pem.Block{
            Type:  "RSA PUBLIC KEY",
            Bytes: pubkey_bytes,
        },
    ), nil
```
</blockquote></details>

Done.
___
*[`pkg/common/cert.go` line 20 at r16](https://reviewable.io/reviews/netsec-ethz/fpki/3#-N0jN4oI688df6Qmyaq3:-N0vjJzI2lTW01tKdKQF:b-896fix) ([raw file](https://github.com/netsec-ethz/fpki/blob/b9eb453e04c289169956efede62ed5a72f6107dd/pkg/common/cert.go#L20)):*
<details><summary><i>Previously, juagargi (Juan A. Garcia Pardo) wrote…</i></summary><blockquote>

wrap errors this way: (note the `%w`)
```go
return []byte{}, fmt.Errorf("RsaPublicKeyToPemBytes | MarshalPKIXPublicKey | %w", err)
```
</blockquote></details>

Done.
___
*[`pkg/common/cert.go` line 45 at r16](https://reviewable.io/reviews/netsec-ethz/fpki/3#-N0jLrgT7fi0M6EVBnQC:-N0vkPWG0RODgkXvH_da:b-896fix) ([raw file](https://github.com/netsec-ethz/fpki/blob/b9eb453e04c289169956efede62ed5a72f6107dd/pkg/common/cert.go#L45)):*
<details><summary><i>Previously, juagargi (Juan A. Garcia Pardo) wrote…</i></summary><blockquote>

do a type assertion instead of an only one case switch:
```go
if rsaPub, ok := pub.(*rsa.PublicKey); ok {
	return rsaPub, nil
}
return nil, errors.New("PemBytesToRsaPublicKey | ParsePKIXPublicKey | Key type is not RSA")
```
</blockquote></details>

Done.
___
*[`pkg/common/cert.go` line 48 at r16](https://reviewable.io/reviews/netsec-ethz/fpki/3#-N0jLh0t60lfVHmzgYF2:-N0vkQN09V6HDPDX9omq:b-896fix) ([raw file](https://github.com/netsec-ethz/fpki/blob/b9eb453e04c289169956efede62ed5a72f6107dd/pkg/common/cert.go#L48)):*
<details><summary><i>Previously, juagargi (Juan A. Garcia Pardo) wrote…</i></summary><blockquote>

remove. No need for a `default` that does nothing.
</blockquote></details>

Done.
___
*[`pkg/common/cert.go` line 70 at r16](https://reviewable.io/reviews/netsec-ethz/fpki/3#-N0jNi8KAPWaOlKvvuyL:-N0vkak-5omtVCsLbWx5:b-896fix) ([raw file](https://github.com/netsec-ethz/fpki/blob/b9eb453e04c289169956efede62ed5a72f6107dd/pkg/common/cert.go#L70)):*
<details><summary><i>Previously, juagargi (Juan A. Garcia Pardo) wrote…</i></summary><blockquote>

In Go, switches are like a collection of `if` conditions. it's more readable to do:
```go
switch{
case block==nil:
	return nil, fmt.Errorf("X509CertFromFile | no pem block in %s", fileName)
case block.Type == "CERTIFICATE":
	return nil, fmt.Errorf("X509CertFromFile | %s contains data other than certificate", fileName)
}
```
</blockquote></details>

Done.
___
*[`pkg/common/crypto.go` line 55 at r16](https://reviewable.io/reviews/netsec-ethz/fpki/3#-N0kPm1V-Jm-cTiItKOg:-N0vtCXuDtBxUm4omqLN:b-896fix) ([raw file](https://github.com/netsec-ethz/fpki/blob/b9eb453e04c289169956efede62ed5a72f6107dd/pkg/common/crypto.go#L55)):*
<details><summary><i>Previously, juagargi (Juan A. Garcia Pardo) wrote…</i></summary><blockquote>

I don't understand the comment
</blockquote></details>

Done.
___
*[`pkg/common/crypto.go` line 90 at r16](https://reviewable.io/reviews/netsec-ethz/fpki/3#-N0kQXCTCPsMzGkQKzVZ:-N0vtKD-3ColsOypQF6l:b-896fix) ([raw file](https://github.com/netsec-ethz/fpki/blob/b9eb453e04c289169956efede62ed5a72f6107dd/pkg/common/crypto.go#L90)):*
<details><summary><i>Previously, juagargi (Juan A. Garcia Pardo) wrote…</i></summary><blockquote>

this is not a deep copy
</blockquote></details>

Done.
___
*[`pkg/common/crypto.go` line 96 at r16](https://reviewable.io/reviews/netsec-ethz/fpki/3#-N0kQnJW2w4IpFd286JV:-N0vtgCz1sZ-Y5BhOouZ:b-896fix) ([raw file](https://github.com/netsec-ethz/fpki/blob/b9eb453e04c289169956efede62ed5a72f6107dd/pkg/common/crypto.go#L96)):*
<details><summary><i>Previously, juagargi (Juan A. Garcia Pardo) wrote…</i></summary><blockquote>

it seems you don't need a deep copy anyways. Same for the other places in this file where you use deep copy.
</blockquote></details>

Done.
___
*[`pkg/common/crypto.go` line 209 at r16](https://reviewable.io/reviews/netsec-ethz/fpki/3#-N0kR8wk0UGkZneW8Kpm:-N0vvDjC8zewwhpVxuXl:b-896fix) ([raw file](https://github.com/netsec-ethz/fpki/blob/b9eb453e04c289169956efede62ed5a72f6107dd/pkg/common/crypto.go#L209)):*
<details><summary><i>Previously, juagargi (Juan A. Garcia Pardo) wrote…</i></summary><blockquote>

```go
return rsa.VerifyPKCS1v15(pubKey, crypto.SHA256, hashOutput[:], rpc.CASignature)
```
</blockquote></details>

Done.
___
*[`pkg/common/json.go` line 13 at r16](https://reviewable.io/reviews/netsec-ethz/fpki/3#-N0kIPjw4auWRXVGjklx:-N0vw3Yf4oxkQ-U0y5Ki:b-896fix) ([raw file](https://github.com/netsec-ethz/fpki/blob/b9eb453e04c289169956efede62ed5a72f6107dd/pkg/common/json.go#L13)):*
<details><summary><i>Previously, juagargi (Juan A. Garcia Pardo) wrote…</i></summary><blockquote>

remember to start the comments of all public functions with the name of the function
</blockquote></details>

Done.
___
*[`pkg/common/json.go` line 101 at r16](https://reviewable.io/reviews/netsec-ethz/fpki/3#-N0kOkaR4mqPt5vgGfX8:-N0w-AX75Ne_x0XCDeAx:b-896fix) ([raw file](https://github.com/netsec-ethz/fpki/blob/b9eb453e04c289169956efede62ed5a72f6107dd/pkg/common/json.go#L101)):*
<details><summary><i>Previously, juagargi (Juan A. Garcia Pardo) wrote…</i></summary><blockquote>

This seems not to be used. If not used, remove.
</blockquote></details>

Done.
___
*[`pkg/pca/config.go` line 10 at r16](https://reviewable.io/reviews/netsec-ethz/fpki/3#-N0kgOIeAubBwwb7Dr7P:-N0wHo7y67AdI_a7U4Ke:b-896fix) ([raw file](https://github.com/netsec-ethz/fpki/blob/b9eb453e04c289169956efede62ed5a72f6107dd/pkg/pca/config.go#L10)):*
<details><summary><i>Previously, juagargi (Juan A. Garcia Pardo) wrote…</i></summary><blockquote>

review all json: tags in the codebase: they should look like
```
CAName string `json:"CAName,omitempty"`
```
(beware of the position of the double quotes)
</blockquote></details>

Done.
___
*[`pkg/pca/pca.go` line 19 at r16](https://reviewable.io/reviews/netsec-ethz/fpki/3#-N0kV42LE4Ft-OzpLPa3:-N0wIeY3-J2QkXOB23u2:b-896fix) ([raw file](https://github.com/netsec-ethz/fpki/blob/b9eb453e04c289169956efede62ed5a72f6107dd/pkg/pca/pca.go#L19)):*
<details><summary><i>Previously, juagargi (Juan A. Garcia Pardo) wrote…</i></summary><blockquote>

keep the length of the lines less than ~ 100 chars
</blockquote></details>

Done.
___
*[`pkg/pca/pca.go` line 22 at r16](https://reviewable.io/reviews/netsec-ethz/fpki/3#-N0kVEtq616GkzmO6BIq:-N0wJ79G7COT2GPTEvKq:b-896fix) ([raw file](https://github.com/netsec-ethz/fpki/blob/b9eb453e04c289169956efede62ed5a72f6107dd/pkg/pca/pca.go#L22)):*
<details><summary><i>Previously, juagargi (Juan A. Garcia Pardo) wrote…</i></summary><blockquote>

The type and its functions seem not to be concurrent friendly.
When creating a type or functions, remember that they will be used concurrently by many different threads (go routines). E.g. `PCA).increaseSerialNumber()` is not thread safe.
If the type or functions cannot be used concurrently, you have to say so in the public documentation.
</blockquote></details>

Done.
___
*[`pkg/pca/pca.go` line 187 at r16](https://reviewable.io/reviews/netsec-ethz/fpki/3#-N0kX4QBAzUTmKyZnSpx:-N0wJUt29DWltXdOzNV2:b-896fix) ([raw file](https://github.com/netsec-ethz/fpki/blob/b9eb453e04c289169956efede62ed5a72f6107dd/pkg/pca/pca.go#L187)):*
<details><summary><i>Previously, juagargi (Juan A. Garcia Pardo) wrote…</i></summary><blockquote>

check this `err`
</blockquote></details>

Done.
___
*[`pkg/pca/pca.go` line  [...]

2022-05-04 16:20 UTC, juagargi requested changes
> Reviewed 2 of 55 files at r26.
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/fpki/3)* status: 155 of 217 files reviewed, 59 unresolved discussions / 0 of 1 LGTMs obtained / 0 of 1 approvals obtained

___
*[`pkg/logverifier/verifier.go` line 52 at r26](https://reviewable.io/reviews/netsec-ethz/fpki/3#-N1Enowp1gYf5GVUb-8b:-N1Enowq8vQ0QhEcz4YY:b-n0lgac) ([raw file](https://github.com/netsec-ethz/fpki/blob/a0d24cb3b1cdaa6c40e4a87329fe6207f998fff2/pkg/logverifier/verifier.go#L52)):*
> ```Go
> 	}
> 
> 	// TODO(Yongzhe): compare two tree heads. If they are the same, directly return nil.
> ```

lowercase


<!-- Sent from Reviewable.io -->

2022-05-11 18:45 UTC, XuYongzhe-ethz reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/fpki/3#-:-N1ndIBPERWMq1e-K_e-:bnfp4nl)* status: :shipit: complete! 1 of 1 LGTMs obtained

___
*[`Makefile` line 17 at r26](https://reviewable.io/reviews/netsec-ethz/fpki/3#-N1Eg8Ik1PP3nk9WmBK_:-N1neMIS4eYao_BWQdOe:b-896fix) ([raw file](https://github.com/netsec-ethz/fpki/blob/a0d24cb3b1cdaa6c40e4a87329fe6207f998fff2/Makefile#L17)):*
<details><summary><i>Previously, juagargi (Juan A. Garcia Pardo) wrote…</i></summary><blockquote>

Remove this.
No files `.DS_Store` should be committed, but there should not exist a rule to remove them from the filesystem.
</blockquote></details>

Done.
___
*[`Makefile` line 18 at r26](https://reviewable.io/reviews/netsec-ethz/fpki/3#-N1EgOibAG4I5fK-Veqi:-N1oR5_k9Bi7XhS_OOEU:b-896fix) ([raw file](https://github.com/netsec-ethz/fpki/blob/a0d24cb3b1cdaa6c40e4a87329fe6207f998fff2/Makefile#L18)):*
<details><summary><i>Previously, juagargi (Juan A. Garcia Pardo) wrote…</i></summary><blockquote>

this file shouldn't be here. Ensure the config_test doesn't create it in the first place (use a temporary file for that instead)
</blockquote></details>

Done.
___
*[`Makefile` line 23 at r26](https://reviewable.io/reviews/netsec-ethz/fpki/3#-N1Ei9i53jk82UWnS-9g:-N1oR6zN9pxvpOt1G26f:b-896fix) ([raw file](https://github.com/netsec-ethz/fpki/blob/a0d24cb3b1cdaa6c40e4a87329fe6207f998fff2/Makefile#L23)):*
<details><summary><i>Previously, juagargi (Juan A. Garcia Pardo) wrote…</i></summary><blockquote>

The plan is to have `bin` with the binaries. The configuration can live somewhere else.
Have the binaries accept a parameter with the location of the config file.
</blockquote></details>

Done.
___
*[`Makefile` line 39 at r26](https://reviewable.io/reviews/netsec-ethz/fpki/3#-N1EiTL8CbN5JFV6lAZx:-N1nf2YO7UpBmPrJErga:b-896fix) ([raw file](https://github.com/netsec-ethz/fpki/blob/a0d24cb3b1cdaa6c40e4a87329fe6207f998fff2/Makefile#L39)):*
<details><summary><i>Previously, juagargi (Juan A. Garcia Pardo) wrote…</i></summary><blockquote>

add an empty line at the end.
</blockquote></details>

Done.
___
*[`README.md` line 2 at r11](https://reviewable.io/reviews/netsec-ethz/fpki/3#-N0VzDus8c03tbU2dxq4:-N1nf4n7DPaHEcFdo_dZ:b-896fix) ([raw file](https://github.com/netsec-ethz/fpki/blob/7994b3f286845f3c8b764ac19fbd9f1fdec6ffcd/README.md#L2)):*
<details><summary><i>Previously, juagargi (Juan A. Garcia Pardo) wrote…</i></summary><blockquote>

Don't write your name in the documentation. There is typically a collaborators file where we would write the authors, or they are just visible with the git history (git log).
</blockquote></details>

Done.
___
*[`README.md` line 6 at r11](https://reviewable.io/reviews/netsec-ethz/fpki/3#-N0VzTSH-5wTDGWvThD-:-N1nf9n0-aPDpXrCZc5K:b-896fix) ([raw file](https://github.com/netsec-ethz/fpki/blob/7994b3f286845f3c8b764ac19fbd9f1fdec6ffcd/README.md#L6)):*
<details><summary><i>Previously, juagargi (Juan A. Garcia Pardo) wrote…</i></summary><blockquote>

Explain what RPC is. Same for the other new acronyms (SPT, etc, but not RPC, and other common ones)
</blockquote></details>

Done.
___
*[`README.md` line 14 at r11](https://reviewable.io/reviews/netsec-ethz/fpki/3#-N0VzlRH4xT7xENTxR_h:-N1nfjGzEyS1HXtg934C:b-896fix) ([raw file](https://github.com/netsec-ethz/fpki/blob/7994b3f286845f3c8b764ac19fbd9f1fdec6ffcd/README.md#L14)):*
<details><summary><i>Previously, juagargi (Juan A. Garcia Pardo) wrote…</i></summary><blockquote>

data for testing should be in the package to test, inside a `testdata` directory
</blockquote></details>

Done.
___
*[`README.md` line 19 at r11](https://reviewable.io/reviews/netsec-ethz/fpki/3#-N0VztQyDvNKBN1m5wus:-N1nflWREA9em5Y__mv3:b-896fix) ([raw file](https://github.com/netsec-ethz/fpki/blob/7994b3f286845f3c8b764ac19fbd9f1fdec6ffcd/README.md#L19)):*
<details><summary><i>Previously, juagargi (Juan A. Garcia Pardo) wrote…</i></summary><blockquote>

should be inside `docs`?
</blockquote></details>

Done.
___
*[`README.md` line 20 at r11](https://reviewable.io/reviews/netsec-ethz/fpki/3#-N0W-02V4QEDsDwx-V4I:-N1nfmDx8wSIn19d-zvI:b-896fix) ([raw file](https://github.com/netsec-ethz/fpki/blob/7994b3f286845f3c8b764ac19fbd9f1fdec6ffcd/README.md#L20)):*
<details><summary><i>Previously, juagargi (Juan A. Garcia Pardo) wrote…</i></summary><blockquote>

should not be here. If you want to keep it, move it inside `doc`
</blockquote></details>

Done.
___
*[`README.md` line 23 at r11](https://reviewable.io/reviews/netsec-ethz/fpki/3#-N0W-4B41AhD-bDDRIVR:-N1nfnu9E990UAjKEgei:b-896fix) ([raw file](https://github.com/netsec-ethz/fpki/blob/7994b3f286845f3c8b764ac19fbd9f1fdec6ffcd/README.md#L23)):*
<details><summary><i>Previously, juagargi (Juan A. Garcia Pardo) wrote…</i></summary><blockquote>

should not be here. Move it to a `testdata` if it's used for a UT, otherwise move it to `tests` if it's used in integration tests.
</blockquote></details>

Done.
___
*[`README.md` line 50 at r11](https://reviewable.io/reviews/netsec-ethz/fpki/3#-N0W-KpS-kPw3VqdCb4H:-N1nfp7D0p_0M9Chw4w6:b-896fix) ([raw file](https://github.com/netsec-ethz/fpki/blob/7994b3f286845f3c8b764ac19fbd9f1fdec6ffcd/README.md#L50)):*
<details><summary><i>Previously, juagargi (Juan A. Garcia Pardo) wrote…</i></summary><blockquote>

Don't give instructions re. different branches, as `pca` will be merged to master.
</blockquote></details>

Done.
___
*[`README.md` line 52 at r11](https://reviewable.io/reviews/netsec-ethz/fpki/3#-N0W-Ww99v8mKJ1WOQ0P:-N1nfs_8C86LBLnYdVO3:b-896fix) ([raw file](https://github.com/netsec-ethz/fpki/blob/7994b3f286845f3c8b764ac19fbd9f1fdec6ffcd/README.md#L52)):*
<details><summary><i>Previously, juagargi (Juan A. Garcia Pardo) wrote…</i></summary><blockquote>

We have to address this TODO now. The UTs don't pass without these changes. Look at the previous comments re. the `testdata` directories.
</blockquote></details>

Done.
___
*[`README.md` line 67 at r11](https://reviewable.io/reviews/netsec-ethz/fpki/3#-N0W-kSQBB2_LC6KCK7o:-N1ng1BdAQs0-AiRsYFz:b-896fix) ([raw file](https://github.com/netsec-ethz/fpki/blob/7994b3f286845f3c8b764ac19fbd9f1fdec6ffcd/README.md#L67)):*
<details><summary><i>Previously, juagargi (Juan A. Garcia Pardo) wrote…</i></summary><blockquote>

Unit tests must not depend on anything else, specially not on a running process. For that we will have the integration tests.
If you need to have some component e.g. answering requests, look at `gomock` to create e.g. a fake server for the test.
</blockquote></details>

Done.
___
*[`pkg/common/crypto.go` line 13 at r16](https://reviewable.io/reviews/netsec-ethz/fpki/3#-N0kPv5X76tzN5EfuxlC:-N1ng2OpAnZb6Of3MTkt:b-896fix) ([raw file](https://github.com/netsec-ethz/fpki/blob/b9eb453e04c289169956efede62ed5a72f6107dd/pkg/common/crypto.go#L13)):*
<details><summary><i>Previously, juagargi (Juan A. Garcia Pardo) wrote…</i></summary><blockquote>

all public types should start their comments with the name of the type, function, etc.
</blockquote></details>

Done.
___
*[`pkg/common/json.go` line 43 at r16](https://reviewable.io/reviews/netsec-ethz/fpki/3#-N0kOB6AD-BVOCa2KqvO:-N1ngNz7DcXUzwwxmuqy:bl8psuv) ([raw file](https://github.com/netsec-ethz/fpki/blob/b9eb453e04c289169956efede62ed5a72f6107dd/pkg/common/json.go#L43)):*
<details><summary><i>Previously, juagargi (Juan A. Garcia Pardo) wrote…</i></summary><blockquote>

there's no need for this
</blockquote></details>

I would suggest to keep it for now. Maybe delete in the future. 
___
*[`pkg/pca/config.go` line 28 at r16](https://reviewable.io/reviews/netsec-ethz/fpki/3#-N0kgjjHB33c0iaAXysQ:-N1nhDpdANMQ7IY7qUJh:by41sha) ([raw file](https://github.com/netsec-ethz/fpki/blob/b9eb453e04c289169956efede62ed5a72f6107dd/pkg/pca/config.go#L28)):*
<details><summary><i>Previously, juagargi (Juan A. Garcia Pardo) wrote…</i></summary><blockquote>

this looks odd. Did [...]

2022-05-11 18:46 UTC, XuYongzhe-ethz reviewed
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/fpki/3)* status: :shipit: complete! 1 of 1 LGTMs obtained

___
*[`Makefile` line 15 at r26](https://reviewable.io/reviews/netsec-ethz/fpki/3#-N1EfclZ8nfuYDxY_Z8z:-N1neKEy42bHJqvkeYyR:bb6un1j) ([raw file](https://github.com/netsec-ethz/fpki/blob/a0d24cb3b1cdaa6c40e4a87329fe6207f998fff2/Makefile#L15)):*
<details><summary><i>Previously, juagargi (Juan A. Garcia Pardo) wrote…</i></summary><blockquote>

Data inside `testdata` is intended to be used by the unit tests.
Unit tests can write data to a temporary directory, not to `testdata`.
Please look at e.g. map_test.go and find a line like this
```go
tempFile := path.Join(os.TempDir(), "root")
```
for inspiration.
</blockquote></details>

Done
___
*[`pkg/common/crypto.go` line 23 at r16](https://reviewable.io/reviews/netsec-ethz/fpki/3#-N0kPQMb873aKWHYpgsk:-N1oRM--43JZYIRlU-K7:b-896fix) ([raw file](https://github.com/netsec-ethz/fpki/blob/b9eb453e04c289169956efede62ed5a72f6107dd/pkg/common/crypto.go#L23)):*
<details><summary><i>Previously, juagargi (Juan A. Garcia Pardo) wrote…</i></summary><blockquote>

move the constants all together (below `SHA256`)
</blockquote></details>

Done.
___
*[`go.mod` line 12 at r11](https://reviewable.io/reviews/netsec-ethz/fpki/3#-N0VsurJBFt40dEuJReZ:-N0X0mxAEFsMsnoPJMSc:bb6un1j) ([raw file](https://github.com/netsec-ethz/fpki/blob/7994b3f286845f3c8b764ac19fbd9f1fdec6ffcd/go.mod#L12)):*
<details><summary><i>Previously, juagargi (Juan A. Garcia Pardo) wrote…</i></summary><blockquote>

Where is prometheus being used? We are not in a stage where we want to add monitoring. This may be added later, once we have all systems working correctly.
</blockquote></details>

Done
___
*[`pkg/logverifier/verifier.go` line 1 at r22](https://reviewable.io/reviews/netsec-ethz/fpki/3#-N0kdk_5EsDZ3xgvEbq7:-N0wCDCh0bq7logQof6c:b-896fix) ([raw file](https://github.com/netsec-ethz/fpki/blob/529f20b791576325768f50e188265bffa25102f8/pkg/logverifier/verifier.go#L1)):*
<details><summary><i>Previously, juagargi (Juan A. Garcia Pardo) wrote…</i></summary><blockquote>

we miss test functions for this package
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-05-12 13:54 UTC, juagargi reviewed
There is only one thing we need to fix to merge this:
Running `go test ./...` must work, without creating a DB, etc.

> Reviewed 1 of 8 files at r22, 15 of 55 files at r26, 9 of 30 files at r28.
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/fpki/3#-:-N1sXz5a4nx7swGEfjAO:b915138)* status: 170 of 241 files reviewed, 2 unresolved discussions / 0 of 1 LGTMs obtained, and 1 stale / 0 of 1 approvals obtained



<!-- Sent from Reviewable.io -->

2022-05-12 14:19 UTC, juagargi reviewed
A bit of a clarification and some pointers:

In two different tests there are calls like this: `updater.NewMapUpdater(db, nil, 233)`
that require a real connection to the DB.
This is not what a unit test is supposed to do.

In the `testgithub.com/netsec-ethz/fpki/pkg/mapserver` 
you can use a mock of the updater. In this test you don't need to check the correct behavior of the updater, as that is tested in some other test. Just check that the mapserver does what it is supposed to do.

In the `testgithub.com/netsec-ethz/fpki/pkg/mapserver/trie`
pass a different db object. Just create a mock type that satisfies the interface instead of getting a real connection to a real DB via `sql.Open`.

For everything to work you will need to change the signature of the functions from taking a `sql.DB` to taking an interface (so that your mock object works).
TAL at this example:
- https://dev.to/pancy/mocking-database-in-go-55bo
You can find more info at e.g.
- https://github.com/DATA-DOG/go-sqlmock
- https://medium.com/easyread/unit-test-sql-in-golang-5af19075e68e
- https://pingcap.com/blog/tidb-lite-a-simpler-way-to-unit-test-golang-database-codeetc.

The idea is not to really run the test against a real DB.

> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/fpki/3#-:-N1scG797Ot1W8Rq-jBt:b-nrdvlb)* status: 170 of 241 files reviewed, 2 unresolved discussions / 0 of 1 LGTMs obtained, and 1 stale / 0 of 1 approvals obtained



<!-- Sent from Reviewable.io -->

2022-05-12 20:51 UTC, XuYongzhe-ethz commented
Hi Juan,
I modify the unit tests, so now the `make test` can run without db setup and any error. I moved some unit tests to the integration test, because the read and write from the db is necessary for these tests. You can run the test using scripts:

`make test`: test the unit tests
 `make all`: This will generate the executables, start mysql server and set db and tables
 `run_integration_test`: Run integration tests (run after `make all`)
`run_log_benchmark`: Run log benchmark (run after `make all`)
`run_smt_benchmark`: Run smt benchmark (run after `make all`)

2022-05-13 13:43 UTC, XuYongzhe-ethz reviewed
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/fpki/3)* status: 170 of 246 files reviewed, 2 unresolved discussions / 0 of 1 LGTMs obtained, and 1 stale / 0 of 1 approvals obtained

___
*[`pkg/logverifier/verifier.go` line 1 at r22](https://reviewable.io/reviews/netsec-ethz/fpki/3#-N0kdk_5EsDZ3xgvEbq7:-N1xeI0v9bfQ6-zxNPkJ:b-896fix) ([raw file](https://github.com/netsec-ethz/fpki/blob/529f20b791576325768f50e188265bffa25102f8/pkg/logverifier/verifier.go#L1)):*
<details><summary><i>Previously, XuYongzhe-ethz wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-05-19 15:36 UTC, juagargi approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 15 files at r31, 2 of 20 files at r34, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/fpki/3#-:-N2RxaRw4VWkMnZ5R5ZN:bnfp4nl)* status: :shipit: complete! 1 of 1 LGTMs obtained, and 1 stale



<!-- Sent from Reviewable.io -->

2022-05-19 15:38 UTC, merged