Map Server as a Service
netsec-ethz/fpki pull request #44
Opened 2023-06-30 09:17 UTC by juagargi

There should exist a mapserver binary that can be run as a service, with its `systemd` service file and all.

This PR closes #26

2023-08-11 13:28 UTC, juagargi commented
> [x] Examine the options to report errors

We can use Prometheus (ideal) or a script to send an email in our server if the `systemd` service crashes.
For now, I've created a `systemd` service file.

2023-10-09 19:22 UTC, cyrill-k requested changes
> Reviewed 31 of 186 files at r1, 10 of 11 files at r2, 147 of 147 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/fpki/44)* status: all files reviewed, 8 unresolved discussions / 0 of 1 LGTMs obtained / 0 of 1 approvals obtained

___
*[`cmd/mapserver/config.go` line 12 at r3](https://reviewable.io/reviews/netsec-ethz/fpki/44#-NgK6wwq8Xd5MXk_hSUd:-NgK6wwq8Xd5MXk_hSUe:b-4n9g8f) ([raw file](https://github.com/netsec-ethz/fpki/blob/88d35cce487fc32ede911a0a19b172a72afc9492/cmd/mapserver/config.go#L12)):*
> ```Go
> 
> type Config struct {
> 	CTLogServerURL     string
> ```

Should we already support fetching from multiple CT logs?
Also, do we need the id and public key of the log to verify the MHT inclusion proof in the CT log's append-only data structure?
___
*[`cmd/mapserver/mapserver.go` line 112 at r3](https://reviewable.io/reviews/netsec-ethz/fpki/44#-NgKD8Mf1g4-roq6CWkC:-NgKD8Mf1g4-roq6CWkD:b-mee7ka) ([raw file](https://github.com/netsec-ethz/fpki/blob/88d35cce487fc32ede911a0a19b172a72afc9492/cmd/mapserver/mapserver.go#L112)):*
> ```Go
> }
> 
> func (s *MapServer) pruneAndUpdate(ctx context.Context) {
> ```

This is not really a complaint, it is most likely just my ignorance with golang parallelism ;D
But why did you not just normally return the error for the `prune` and `update` function below and only use the `updateErrChan` here and in `PruneAndUpdate`?
Wouldn't that make the code easier to understand?
___
*[`cmd/mapserver/mapserver.go` line 137 at r3](https://reviewable.io/reviews/netsec-ethz/fpki/44#-NgKAz4CDxepO3xLHQpB:-NgKAz4CDxepO3xLHQpC:b-cohfqw) ([raw file](https://github.com/netsec-ethz/fpki/blob/88d35cce487fc32ede911a0a19b172a72afc9492/cmd/mapserver/mapserver.go#L137)):*
> ```Go
> 	err := s.Updater.Conn.PruneCerts(ctx, time.Now())
> 	if err != nil {
> 		s.updateErrChan <- fmt.Errorf("pruning: %w", err)
> ```

Don't we have to abort if an error was returned? (i.e., add a `return` statement here)?
___
*[`pkg/db/mysql/conf.go` line 68 at r3](https://reviewable.io/reviews/netsec-ethz/fpki/44#-NgKFMZrEEIENG80IUGk:-NgKFMZrEEIENG80IUGl:baghtu8) ([raw file](https://github.com/netsec-ethz/fpki/blob/88d35cce487fc32ede911a0a19b172a72afc9492/pkg/db/mysql/conf.go#L68)):*
> ```Go
> 			"collation":         "binary",
> 			"maxAllowedPacket":  "1073741824", // 1G (cannot use "1G" as the driver uses Atoi)
> 			"parseTime":         "true",       // driver parses DATETIME into time.Time
> ```

what is this field used for?
___
*[`pkg/db/mysql/mysql_test.go` line 306 at r3](https://reviewable.io/reviews/netsec-ethz/fpki/44#-NgKGL0l3YoebuhGLEPb:-NgKGL0l3YoebuhGLEPc:b-yq6rqj) ([raw file](https://github.com/netsec-ethz/fpki/blob/88d35cce487fc32ede911a0a19b172a72afc9492/pkg/db/mysql/mysql_test.go#L306)):*
> ```Go
> 	require.NoError(t, err)
> 
> 	// Now test that prune removes the to leaves from b.com and four certificates from c.com,
> ```

"... two leaves ..."
___
*[`pkg/mapserver/updater/updater.go` line 99 at r3](https://reviewable.io/reviews/netsec-ethz/fpki/44#-NgKIjZL7P6Wvx4WPqaa:-NgKIjZL7P6Wvx4WPqab:b-cq2li) ([raw file](https://github.com/netsec-ethz/fpki/blob/88d35cce487fc32ede911a0a19b172a72afc9492/pkg/mapserver/updater/updater.go#L99)):*
> ```Go
> 		// Store the last index obtained from the fetcher as updated.
> 		u.lastUpdatedIndex += int64(n)
> 		err = u.Conn.UpdateLastCertIndexWritten(ctx, url, u.lastUpdatedIndex)
> ```

Should we also check that the returned certificates are really the ones added by the CT log server (i.e., verify MHT inclusion proof)?
Or, if we postpone doing this check for later, should we already add a placeholder function that does this and maybe the necessary data structures? Or just add a todo?
It would require to do one more request to the CT log (https://datatracker.ietf.org/doc/html/rfc6962#page-19) to get the consistency proof between two signed tree heads (last index written and current index) and to store the signed tree head at the last updated index.
___
*[`pkg/util/time.go` line 32 at r3](https://reviewable.io/reviews/netsec-ethz/fpki/44#-NgKqHlECOM7PJ6Gf1kP:-NgKqHlECOM7PJ6Gf1kQ:b1suncw) ([raw file](https://github.com/netsec-ethz/fpki/blob/88d35cce487fc32ede911a0a19b172a72afc9492/pkg/util/time.go#L32)):*
> ```Go
> // parseInteger parses a string into a integer. The type can be explicitly indicated or inferred
> // from min and max.
> // Note that with Go 1.20
> ```

incomplete sentence
___
*[`tests/integration/domainowner_pca_policlog_interaction/main.go` line 3 at r3](https://reviewable.io/reviews/netsec-ethz/fpki/44#-NgKqfZnB5letcP4G-TV:-NgKqfZnB5letcP4G-TW:b-8gumai) ([raw file](https://github.com/netsec-ethz/fpki/blob/88d35cce487fc32ede911a0a19b172a72afc9492/tests/integration/domainowner_pca_policlog_interaction/main.go#L3)):*
> ```Go
> package main
> 
> // import (
> ```

should this file be completely removed?


<!-- Sent from Reviewable.io -->

2023-10-29 20:26 UTC, juagargi reviewed
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/fpki/44)* status: 165 of 193 files reviewed, 8 unresolved discussions / 0 of 1 LGTMs obtained / 0 of 1 approvals obtained

___
*[`pkg/db/mysql/conf.go` line 68 at r3](https://reviewable.io/reviews/netsec-ethz/fpki/44#-NgKFMZrEEIENG80IUGk:-Nhwwnmz5yG41wB42uuE:b-ko7lmq) ([raw file](https://github.com/netsec-ethz/fpki/blob/88d35cce487fc32ede911a0a19b172a72afc9492/pkg/db/mysql/conf.go#L68)):*
<details><summary><i>Previously, cyrill-k wrote…</i></summary><blockquote>

what is this field used for?
</blockquote></details>

To allow the driver to parse its internal representation into Go's `time.Time`
___
*[`pkg/db/mysql/mysql_test.go` line 306 at r3](https://reviewable.io/reviews/netsec-ethz/fpki/44#-NgKGL0l3YoebuhGLEPb:-NhwzC0k5Uyw1tTbmK5a:b-896fix) ([raw file](https://github.com/netsec-ethz/fpki/blob/88d35cce487fc32ede911a0a19b172a72afc9492/pkg/db/mysql/mysql_test.go#L306)):*
<details><summary><i>Previously, cyrill-k wrote…</i></summary><blockquote>

"... two leaves ..."
</blockquote></details>

Done.
___
*[`pkg/mapserver/updater/updater.go` line 99 at r3](https://reviewable.io/reviews/netsec-ethz/fpki/44#-NgKIjZL7P6Wvx4WPqaa:-Nhx5GD_2blq8MuTvAfE:byl8opp) ([raw file](https://github.com/netsec-ethz/fpki/blob/88d35cce487fc32ede911a0a19b172a72afc9492/pkg/mapserver/updater/updater.go#L99)):*
<details><summary><i>Previously, cyrill-k wrote…</i></summary><blockquote>

Should we also check that the returned certificates are really the ones added by the CT log server (i.e., verify MHT inclusion proof)?
Or, if we postpone doing this check for later, should we already add a placeholder function that does this and maybe the necessary data structures? Or just add a todo?
It would require to do one more request to the CT log (https://datatracker.ietf.org/doc/html/rfc6962#page-19) to get the consistency proof between two signed tree heads (last index written and current index) and to store the signed tree head at the last updated index.
</blockquote></details>

Done.
As discussed offline, this is only partially implemented by just leaving the real verification to be done later, and flagged with two `TODO`.
___
*[`pkg/util/time.go` line 32 at r3](https://reviewable.io/reviews/netsec-ethz/fpki/44#-NgKqHlECOM7PJ6Gf1kP:-Nhx6-AD9Nw69XO0vdQp:b-fb6pcg) ([raw file](https://github.com/netsec-ethz/fpki/blob/88d35cce487fc32ede911a0a19b172a72afc9492/pkg/util/time.go#L32)):*
<details><summary><i>Previously, cyrill-k wrote…</i></summary><blockquote>

incomplete sentence
</blockquote></details>

Done. Removed complete function, as it was a leftover of a previous attempt.
___
*[`tests/integration/domainowner_pca_policlog_interaction/main.go` line 3 at r3](https://reviewable.io/reviews/netsec-ethz/fpki/44#-NgKqfZnB5letcP4G-TV:-Nhx6BhN5ZYmvrWV-VHo:bqdoqyc) ([raw file](https://github.com/netsec-ethz/fpki/blob/88d35cce487fc32ede911a0a19b172a72afc9492/tests/integration/domainowner_pca_policlog_interaction/main.go#L3)):*
<details><summary><i>Previously, cyrill-k wrote…</i></summary><blockquote>

should this file be completely removed?
</blockquote></details>

I want to keep it in `master`, as we should eventually bring a proper integration test for the domain owner and the PCA interactions. I assume that this could help, but let me know if you prefer to have it removed.
___
*[`cmd/mapserver/config.go` line 12 at r3](https://reviewable.io/reviews/netsec-ethz/fpki/44#-NgK6wwq8Xd5MXk_hSUd:-Nhx5EWx26HmHwGJIOqd:b-896fix) ([raw file](https://github.com/netsec-ethz/fpki/blob/88d35cce487fc32ede911a0a19b172a72afc9492/cmd/mapserver/config.go#L12)):*
<details><summary><i>Previously, cyrill-k wrote…</i></summary><blockquote>

Should we already support fetching from multiple CT logs?
Also, do we need the id and public key of the log to verify the MHT inclusion proof in the CT log's append-only data structure?
</blockquote></details>

Done.
___
*[`cmd/mapserver/mapserver.go` line 112 at r3](https://reviewable.io/reviews/netsec-ethz/fpki/44#-NgKD8Mf1g4-roq6CWkC:-Nhx3Ge2-sNl6zFrkw62:bw0r358) ([raw file](https://github.com/netsec-ethz/fpki/blob/88d35cce487fc32ede911a0a19b172a72afc9492/cmd/mapserver/mapserver.go#L112)):*
<details><summary><i>Previously, cyrill-k wrote…</i></summary><blockquote>

This is not really a complaint, it is most likely just my ignorance with golang parallelism ;D
But why did you not just normally return the error for the `prune` and `update` function below and only use the `updateErrChan` here and in `PruneAndUpdate`?
Wouldn't that make the code easier to understand?
</blockquote></details>

You are right. The function `pruneAndUpdate` is unnecessarily complex; it's now simpler by having `prune` and `update` directly return the error. Additionally, the previous code there had a bug.

As for the `updateChan`, we need it because the function could be called from several goroutines at the same time, and we want them to wait. Another sync mechanism like a mutex would have worked as well.
___
*[`cmd/mapserver/mapserver.go` line 137 at r3](https://reviewable.io/reviews/netsec-ethz/fpki/44#-NgKAz4CDxepO3xLHQpB:-Nhx5Crz4AbFEZWUBMUg:b-896fix) ([raw file](https://github.com/netsec-ethz/fpki/blob/88d35cce487fc32ede911a0a19b172a72afc9492/cmd/mapserver/mapserver.go#L137)):*
<details><summary><i>Previously, cyrill-k wrote…</i></summary><blockquote>

Don't we have to abort if an error was returned? (i.e., add a `return` statement here)?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-10-30 10:32 UTC, cyrill-k requested changes
> Reviewed 32 of 32 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/fpki/44)* status: all files reviewed, 6 unresolved discussions / 0 of 1 LGTMs obtained / 0 of 1 approvals obtained

___
*[`cmd/ingest/processor.go` line 176 at r4](https://reviewable.io/reviews/netsec-ethz/fpki/44#-Ni-4rG9E7wi0IiOzVxd:-Ni-4rG9E7wi0IiOzVxe:br5frqo) ([raw file](https://github.com/netsec-ethz/fpki/blob/c78755f8d48382e31e40a0c6bc67bf71788f0d3f/cmd/ingest/processor.go#L176)):*
> ```Go
> 
> 	parseFunction := func(fields []string, lineNo int) error {
> 		// First avoid even parsing already expired certs.
> ```

One thing to keep in mind is that in some cases, the csv fields are not properly escaped, which may lead to issues because the expiration column is shifted. We could implement a sanity check by counting the number of columns and not use the expiration column if the count is larger than 8?
___
*[`pkg/mapserver/logfetcher/logfetcher.go` line 116 at r4](https://reviewable.io/reviews/netsec-ethz/fpki/44#-Ni-0VYlBniob0BUSww7:-Ni-0VYlBniob0BUSww8:bgn068r) ([raw file](https://github.com/netsec-ethz/fpki/blob/c78755f8d48382e31e40a0c6bc67bf71788f0d3f/pkg/mapserver/logfetcher/logfetcher.go#L116)):*
> ```Go
> 	return State{
> 		Size: sth.TreeSize,
> 		STH:  sth.TreeHeadSignature.Signature,
> ```

Shouldn't this be the complete STH and not just the signature?
Because I think the `SHA256RootHash` may also be needed during verification.
Also, the signature is either (1) already verified by the GetSTH() function or (2) must be verified later in which case all the other STH fields must also be provided to perform the verification.
___
*[`pkg/mapserver/updater/updater.go` line 106 at r4](https://reviewable.io/reviews/netsec-ethz/fpki/44#-NhzrBbLEtwUWHetT4Vb:-NhzrBbLEtwUWHetT4Vc:bitsfya) ([raw file](https://github.com/netsec-ethz/fpki/blob/c78755f8d48382e31e40a0c6bc67bf71788f0d3f/pkg/mapserver/updater/updater.go#L106)):*
> ```Go
> 	// intermediate step).
> 	// We may want to start a transaction in the DB at the StartFetchingRemaining and commit it
> 	// only if the verification of all batches is alright.
> ```

That's a good point.
One potential workaround for this is to perform the append-only verification in two steps: one for the batch entries and one for the entries after the batch before the current size.
Let N = old tree size, B = batch size and M (> N + B) = the current size. We request two consistency proofs from the CT log: [N, N+B] and [N+B, M]. First, we verify that appending the certificates in the batch results in the correct MHT root value at N+B. Then, we verify that the append-only property between N+B and M is satisfied (without looking at the actual certificates that it contains)

The only potential issue that I see is that a CT log server may not provide consistency proofs for arbitrary ranges within [N, M], since the RFC states that "Both tree sizes must be from existing v1 STHs (Signed Tree Heads)." (see https://datatracker.ietf.org/doc/html/rfc6962#section-4.4). Although, when I checked with the argon 2023 log, it seemed to work for arbitrary ranges (https://ct.googleapis.com/logs/argon2023/ct/v1/get-sth-consistency?first=1000000&second=2000011)
___
*[`pkg/mapserver/updater/updater.go` line 217 at r4](https://reviewable.io/reviews/netsec-ethz/fpki/44#-NhzvYW-4HnsA_DqrTPM:-NhzvYW-4HnsA_DqrTPN:bdpigui) ([raw file](https://github.com/netsec-ethz/fpki/blob/c78755f8d48382e31e40a0c6bc67bf71788f0d3f/pkg/mapserver/updater/updater.go#L217)):*
> ```Go
> 	ctx context.Context,
> 	leafCerts []*ctx509.Certificate,
> 	chains [][]*ctx509.Certificate,
> ```

It may be more efficient to pass the actual leaf content to this function instead of recreating the CT log leaf data structure. But this would probably need to be evaluated once this function is implemented, so I would suggest to just leave a comment.
___
*[`tests/integration/domainowner_pca_policlog_interaction/main.go` line 3 at r3](https://reviewable.io/reviews/netsec-ethz/fpki/44#-NgKqfZnB5letcP4G-TV:-NhzwKfTArOUQFFlSfuc:b-kbr31t) ([raw file](https://github.com/netsec-ethz/fpki/blob/88d35cce487fc32ede911a0a19b172a72afc9492/tests/integration/domainowner_pca_policlog_interaction/main.go#L3)):*
<details><summary><i>Previously, juagargi (Juan A. Garcia Pardo) wrote…</i></summary><blockquote>

I want to keep it in `master`, as we should eventually bring a proper integration test for the domain owner and the PCA interactions. I assume that this could help, but let me know if you prefer to have it removed.
</blockquote></details>

No, I don't have any strong preferences. Either way is fine for me.
___
*[`cmd/mapserver/config.go` line 12 at r3](https://reviewable.io/reviews/netsec-ethz/fpki/44#-NgK6wwq8Xd5MXk_hSUd:-Nhzp1ccBXS1dOuBX957:bjb66t3) ([raw file](https://github.com/netsec-ethz/fpki/blob/88d35cce487fc32ede911a0a19b172a72afc9492/cmd/mapserver/config.go#L12)):*
<details><summary><i>Previously, juagargi (Juan A. Garcia Pardo) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

How about the id and public key of the log to verify the MHT inclusion proof? Shouldn't this also be added in the config file?


<!-- Sent from Reviewable.io -->

2023-10-31 08:22 UTC, juagargi reviewed
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/fpki/44)* status: all files reviewed, 6 unresolved discussions / 0 of 1 LGTMs obtained / 0 of 1 approvals obtained

___
*[`cmd/ingest/processor.go` line 176 at r4](https://reviewable.io/reviews/netsec-ethz/fpki/44#-Ni-4rG9E7wi0IiOzVxd:-Ni0kG-V3HH3e2UMTwBb:b-zcrczm) ([raw file](https://github.com/netsec-ethz/fpki/blob/c78755f8d48382e31e40a0c6bc67bf71788f0d3f/cmd/ingest/processor.go#L176)):*
<details><summary><i>Previously, cyrill-k wrote…</i></summary><blockquote>

One thing to keep in mind is that in some cases, the csv fields are not properly escaped, which may lead to issues because the expiration column is shifted. We could implement a sanity check by counting the number of columns and not use the expiration column if the count is larger than 8?
</blockquote></details>

Do you have any records as an example? Maybe we can easily heal them.
___
*[`pkg/mapserver/logfetcher/logfetcher.go` line 116 at r4](https://reviewable.io/reviews/netsec-ethz/fpki/44#-Ni-0VYlBniob0BUSww7:-Ni0kgE_5_4fGxbB-0gg:bqoxw9c) ([raw file](https://github.com/netsec-ethz/fpki/blob/c78755f8d48382e31e40a0c6bc67bf71788f0d3f/pkg/mapserver/logfetcher/logfetcher.go#L116)):*
<details><summary><i>Previously, cyrill-k wrote…</i></summary><blockquote>

Shouldn't this be the complete STH and not just the signature?
Because I think the `SHA256RootHash` may also be needed during verification.
Also, the signature is either (1) already verified by the GetSTH() function or (2) must be verified later in which case all the other STH fields must also be provided to perform the verification.
</blockquote></details>

I have no idea what will be needed honestly. I've added the `STH` mainly as a placeholder. But same as with the configuration, the implementer may need to serialize the complete `TreeHeadSignature` to bytes and back. I think for now it is clear that the info can be obtained and transmitted to the appropriate location in the code.
___
*[`pkg/mapserver/updater/updater.go` line 106 at r4](https://reviewable.io/reviews/netsec-ethz/fpki/44#-NhzrBbLEtwUWHetT4Vb:-Ni0lFfh9KXvfuODPAph:b69gmet) ([raw file](https://github.com/netsec-ethz/fpki/blob/c78755f8d48382e31e40a0c6bc67bf71788f0d3f/pkg/mapserver/updater/updater.go#L106)):*
<details><summary><i>Previously, cyrill-k wrote…</i></summary><blockquote>

That's a good point.
One potential workaround for this is to perform the append-only verification in two steps: one for the batch entries and one for the entries after the batch before the current size.
Let N = old tree size, B = batch size and M (> N + B) = the current size. We request two consistency proofs from the CT log: [N, N+B] and [N+B, M]. First, we verify that appending the certificates in the batch results in the correct MHT root value at N+B. Then, we verify that the append-only property between N+B and M is satisfied (without looking at the actual certificates that it contains)

The only potential issue that I see is that a CT log server may not provide consistency proofs for arbitrary ranges within [N, M], since the RFC states that "Both tree sizes must be from existing v1 STHs (Signed Tree Heads)." (see https://datatracker.ietf.org/doc/html/rfc6962#section-4.4). Although, when I checked with the argon 2023 log, it seemed to work for arbitrary ranges (https://ct.googleapis.com/logs/argon2023/ct/v1/get-sth-consistency?first=1000000&second=2000011)
</blockquote></details>

My thought was: we cannot be confident that the two STHs (old and new one) are correct until we request the new one. And having the new STH way in the future size is not helping verify each batch. We can get consistency proofs for the batches, but it will yield intermediate top nodes that cannot be verified, because we won't get the whole `TreeSignedHead` structure in the intermediate proofs (or will we? with the public signature and all? The student taking the project should test this, and read the RFC)
___
*[`pkg/mapserver/updater/updater.go` line 217 at r4](https://reviewable.io/reviews/netsec-ethz/fpki/44#-NhzvYW-4HnsA_DqrTPM:-Ni3nw5A6e86JUYI2vU_:bsbysvs) ([raw file](https://github.com/netsec-ethz/fpki/blob/c78755f8d48382e31e40a0c6bc67bf71788f0d3f/pkg/mapserver/updater/updater.go#L217)):*
<details><summary><i>Previously, cyrill-k wrote…</i></summary><blockquote>

It may be more efficient to pass the actual leaf content to this function instead of recreating the CT log leaf data structure. But this would probably need to be evaluated once this function is implemented, so I would suggest to just leave a comment.
</blockquote></details>

True, added comment
___
*[`tests/integration/domainowner_pca_policlog_interaction/main.go` line 3 at r3](https://reviewable.io/reviews/netsec-ethz/fpki/44#-NgKqfZnB5letcP4G-TV:-Ni3o0n3CDtJ0qbyCanw:b-d7wrp7) ([raw file](https://github.com/netsec-ethz/fpki/blob/88d35cce487fc32ede911a0a19b172a72afc9492/tests/integration/domainowner_pca_policlog_interaction/main.go#L3)):*
<details><summary><i>Previously, cyrill-k wrote…</i></summary><blockquote>

No, I don't have any strong preferences. Either way is fine for me.
</blockquote></details>

I'm removing it :smiley: 
___
*[`cmd/mapserver/config.go` line 12 at r3](https://reviewable.io/reviews/netsec-ethz/fpki/44#-NgK6wwq8Xd5MXk_hSUd:-Ni0kNLo2xNwZFge9NWf:bwr60qr) ([raw file](https://github.com/netsec-ethz/fpki/blob/88d35cce487fc32ede911a0a19b172a72afc9492/cmd/mapserver/config.go#L12)):*
<details><summary><i>Previously, cyrill-k wrote…</i></summary><blockquote>

How about the id and public key of the log to verify the MHT inclusion proof? Shouldn't this also be added in the config file?
</blockquote></details>

I would let the implementer choose how to do it, but yes, this should be part of the config as well. Since we are not needing it at the moment, I prefer not to modify it until we know what we want exactly.


<!-- Sent from Reviewable.io -->

2023-11-10 10:37 UTC, cyrill-k requested changes
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/fpki/44)* status: all files reviewed, 4 unresolved discussions / 0 of 1 LGTMs obtained / 0 of 1 approvals obtained

___
*[`cmd/ingest/processor.go` line 176 at r4](https://reviewable.io/reviews/netsec-ethz/fpki/44#-Ni-4rG9E7wi0IiOzVxd:-Niskf7MCRyic-20Ua9v:b-2bcx7h) ([raw file](https://github.com/netsec-ethz/fpki/blob/c78755f8d48382e31e40a0c6bc67bf71788f0d3f/cmd/ingest/processor.go#L176)):*
<details><summary><i>Previously, juagargi (Juan A. Garcia Pardo) wrote…</i></summary><blockquote>

Do you have any records as an example? Maybe we can easily heal them.
</blockquote></details>

I couldn't find an example in the Alexa top 100K certificates, but the problem was that the last two columns (NotBefore and NotAfter) are shifted if the common name (or a SAN entry) contains one of multiple commas. As a workaround, we could simply use the last entry for the expiration, i.e., `fields[len(fields)-(8-ExpirationColumn)]`
___
*[`pkg/mapserver/logfetcher/logfetcher.go` line 116 at r4](https://reviewable.io/reviews/netsec-ethz/fpki/44#-Ni-0VYlBniob0BUSww7:-NisIh509jfTzeeFbgVC:bilimoj) ([raw file](https://github.com/netsec-ethz/fpki/blob/c78755f8d48382e31e40a0c6bc67bf71788f0d3f/pkg/mapserver/logfetcher/logfetcher.go#L116)):*
<details><summary><i>Previously, juagargi (Juan A. Garcia Pardo) wrote…</i></summary><blockquote>

I have no idea what will be needed honestly. I've added the `STH` mainly as a placeholder. But same as with the configuration, the implementer may need to serialize the complete `TreeHeadSignature` to bytes and back. I think for now it is clear that the info can be obtained and transmitted to the appropriate location in the code.
</blockquote></details>

I see, in that case I would suggest to add a comment that we may need to change this field to implement the CT log verification.
___
*[`pkg/mapserver/updater/updater.go` line 106 at r4](https://reviewable.io/reviews/netsec-ethz/fpki/44#-NhzrBbLEtwUWHetT4Vb:-NisJW3L0fM-4FIDgc3W:bh2zb6t) ([raw file](https://github.com/netsec-ethz/fpki/blob/c78755f8d48382e31e40a0c6bc67bf71788f0d3f/pkg/mapserver/updater/updater.go#L106)):*
<details><summary><i>Previously, juagargi (Juan A. Garcia Pardo) wrote…</i></summary><blockquote>

My thought was: we cannot be confident that the two STHs (old and new one) are correct until we request the new one. And having the new STH way in the future size is not helping verify each batch. We can get consistency proofs for the batches, but it will yield intermediate top nodes that cannot be verified, because we won't get the whole `TreeSignedHead` structure in the intermediate proofs (or will we? with the public signature and all? The student taking the project should test this, and read the RFC)
</blockquote></details>

Maybe I can reformulate it:
Again, let N = old tree size, B = batch size and M (> N + B) = the current size.

Ideally, we would like to do the verification per batch, which works as follows:
(1) Request STH at N+B with MHT root value R
(2) Add the certificates in the batch [N, N+B] and calculate the new MHT root value R'
(2) Verify that adding these certificates results results in the correct MHT root value (R==R')
(3) Accept batch certificates and add to the DB

However, since we cannot fetch the STH at arbitrary tree sizes, your current proposal is to accumulate all batches between N and M and then verify that the root value is correct:
(1) Request STH at M with MHT root value R
(2) Start DB transaction
(3) for all batches ([N,N+B], [N+B,N+2B],...[N+XB,M]): add certificates in batch and calculate the final root value R' at tree size M
(4) Verify that adding all batches results in the correct MHT root value (R==R')
(5) Commit DB transaction

However, I'm not sure how well this will work because we have to lock tables, have huge transactions, etc. My suggestion is the following:
(1) Request STH at M with MHT root value R
(2) for all batches except the last one ([N, N+B], [N+B, N+2B], ..., [N+(X-1)B, N+XB]), do the following:
(3a) for the batch [S, S+B], add all certificates in the batch which results in a new MHT root value R'
(3b) request consistency proof for [S+B, M] (as I said before, it is not clear from the RFC if this must be supported by a CT log servers)
(3c) verify that the consistency proof is valid given the two tree roots R' at S+B and R at M
(3d) if the consistency proof is valid, add the batch to the DB
(4) Verify and add the last batch [N+XB, M] as described in the first approach

The idea is that due to the append-only property of the MHT, it is not a problem if the MHT tree root at R' in (3c) is not signed by an STH.
Because if the attacker can fabricate a batch B_0 (resulting in the root value R_0') which is different from the actual batch B_1 (resulting in to root value R_1'), such that there exist consistency proofs for both root values (consistency [R_0', R] and consistency [R_1', R]), the append-only property of the MHT would be violated.
Someone should properly verify this.

This became much longer than I expected :sweat_smile: 
I would suggest that we merge this as it is right now and create a new gitlab issue for all concerns regarding the (efficient) validation of CT log entries and copy all the discussion there.
What do you think?
___
*[`cmd/mapserver/config.go` line 12 at r3](https://reviewable.io/reviews/netsec-ethz/fpki/44#-NgK6wwq8Xd5MXk_hSUd:-NisIMvi7wy9RyIIfzqO:bvmy27t) ([raw file](https://github.com/netsec-ethz/fpki/blob/88d35cce487fc32ede911a0a19b172a72afc9492/cmd/mapserver/config.go#L12)):*
<details><summary><i>Previously, juagargi (Juan A. Garcia Pardo) wrote…</i></summary><blockquote>

I would let the implementer choose how to do it, but yes, this should be part of the config as well. Since we are not needing it at the moment, I prefer not to modify it until we know what we want exactly.
</blockquote></details>

Ok :thumbsup: 


<!-- Sent from Reviewable.io -->

2023-12-18 09:43 UTC, juagargi reviewed
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/fpki/44)* status: all files reviewed, 4 unresolved discussions / 0 of 1 LGTMs obtained / 0 of 1 approvals obtained

___
*[`cmd/ingest/processor.go` line 176 at r4](https://reviewable.io/reviews/netsec-ethz/fpki/44#-Ni-4rG9E7wi0IiOzVxd:-NlwBCVt1LHdFa7Jz0SI:b-yn8lrq) ([raw file](https://github.com/netsec-ethz/fpki/blob/c78755f8d48382e31e40a0c6bc67bf71788f0d3f/cmd/ingest/processor.go#L176)):*
<details><summary><i>Previously, cyrill-k wrote…</i></summary><blockquote>

I couldn't find an example in the Alexa top 100K certificates, but the problem was that the last two columns (NotBefore and NotAfter) are shifted if the common name (or a SAN entry) contains one of multiple commas. As a workaround, we could simply use the last entry for the expiration, i.e., `fields[len(fields)-(8-ExpirationColumn)]`
</blockquote></details>

Done.
But we need to find examples like those you mention, just to check that nothing else will be broken.
___
*[`pkg/mapserver/logfetcher/logfetcher.go` line 116 at r4](https://reviewable.io/reviews/netsec-ethz/fpki/44#-Ni-0VYlBniob0BUSww7:-NlwAvqY2RTKRMmlmLu-:b-896fix) ([raw file](https://github.com/netsec-ethz/fpki/blob/c78755f8d48382e31e40a0c6bc67bf71788f0d3f/pkg/mapserver/logfetcher/logfetcher.go#L116)):*
<details><summary><i>Previously, cyrill-k wrote…</i></summary><blockquote>

I see, in that case I would suggest to add a comment that we may need to change this field to implement the CT log verification.
</blockquote></details>

Done.
___
*[`pkg/mapserver/updater/updater.go` line 106 at r4](https://reviewable.io/reviews/netsec-ethz/fpki/44#-NhzrBbLEtwUWHetT4Vb:-NlwIgOV67FZgf6m4jIx:brx75aw) ([raw file](https://github.com/netsec-ethz/fpki/blob/c78755f8d48382e31e40a0c6bc67bf71788f0d3f/pkg/mapserver/updater/updater.go#L106)):*
<details><summary><i>Previously, cyrill-k wrote…</i></summary><blockquote>

Maybe I can reformulate it:
Again, let N = old tree size, B = batch size and M (> N + B) = the current size.

Ideally, we would like to do the verification per batch, which works as follows:
(1) Request STH at N+B with MHT root value R
(2) Add the certificates in the batch [N, N+B] and calculate the new MHT root value R'
(2) Verify that adding these certificates results results in the correct MHT root value (R==R')
(3) Accept batch certificates and add to the DB

However, since we cannot fetch the STH at arbitrary tree sizes, your current proposal is to accumulate all batches between N and M and then verify that the root value is correct:
(1) Request STH at M with MHT root value R
(2) Start DB transaction
(3) for all batches ([N,N+B], [N+B,N+2B],...[N+XB,M]): add certificates in batch and calculate the final root value R' at tree size M
(4) Verify that adding all batches results in the correct MHT root value (R==R')
(5) Commit DB transaction

However, I'm not sure how well this will work because we have to lock tables, have huge transactions, etc. My suggestion is the following:
(1) Request STH at M with MHT root value R
(2) for all batches except the last one ([N, N+B], [N+B, N+2B], ..., [N+(X-1)B, N+XB]), do the following:
(3a) for the batch [S, S+B], add all certificates in the batch which results in a new MHT root value R'
(3b) request consistency proof for [S+B, M] (as I said before, it is not clear from the RFC if this must be supported by a CT log servers)
(3c) verify that the consistency proof is valid given the two tree roots R' at S+B and R at M
(3d) if the consistency proof is valid, add the batch to the DB
(4) Verify and add the last batch [N+XB, M] as described in the first approach

The idea is that due to the append-only property of the MHT, it is not a problem if the MHT tree root at R' in (3c) is not signed by an STH.
Because if the attacker can fabricate a batch B_0 (resulting in the root value R_0') which is different from the actual batch B_1 (resulting in to root value R_1'), such that there exist consistency proofs for both root values (consistency [R_0', R] and consistency [R_1', R]), the append-only property of the MHT would be violated.
Someone should properly verify this.

This became much longer than I expected :sweat_smile: 
I would suggest that we merge this as it is right now and create a new gitlab issue for all concerns regarding the (efficient) validation of CT log entries and copy all the discussion there.
What do you think?
</blockquote></details>

Done.
Issue is #47, referenced also on a comment in the code.
___
*[`cmd/mapserver/config.go` line 12 at r3](https://reviewable.io/reviews/netsec-ethz/fpki/44#-NgK6wwq8Xd5MXk_hSUd:-Nj7BnaFEiNbuACFv912:b-896fix) ([raw file](https://github.com/netsec-ethz/fpki/blob/88d35cce487fc32ede911a0a19b172a72afc9492/cmd/mapserver/config.go#L12)):*
<details><summary><i>Previously, cyrill-k wrote…</i></summary><blockquote>

Ok :thumbsup:
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-12-18 10:44 UTC, cyrill-k requested changes
> Reviewed 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/fpki/44)* status: all files reviewed, 1 unresolved discussion / 0 of 1 LGTMs obtained / 0 of 1 approvals obtained

___
*[`cmd/ingest/processor.go` line 302 at r6](https://reviewable.io/reviews/netsec-ethz/fpki/44#-NlwVaORBb_3Vg0Mz0e_:-NlwVaORBb_3Vg0Mz0ea:bwcdbzo) ([raw file](https://github.com/netsec-ethz/fpki/blob/94ae7ef04d6332820e64d7125de7c1111eb54387/cmd/ingest/processor.go#L302)):*
> ```Go
> 	s := strings.Split(fields[expirationColumn], ".")
> 	if len(s) != 2 {
> 		return 0, fmt.Errorf("unrecognized timestamp in 7th column: %s", fields[expirationColumn])
> ```

this should probably be "... in the last column: ..."


<!-- Sent from Reviewable.io -->

2023-12-18 13:32 UTC, juagargi reviewed
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/fpki/44)* status: 187 of 195 files reviewed, 1 unresolved discussion / 0 of 1 LGTMs obtained / 0 of 1 approvals obtained

___
*[`cmd/ingest/processor.go` line 302 at r6](https://reviewable.io/reviews/netsec-ethz/fpki/44#-NlwVaORBb_3Vg0Mz0e_:-Nlx76wjE67mUwNwSMtr:b-896fix) ([raw file](https://github.com/netsec-ethz/fpki/blob/94ae7ef04d6332820e64d7125de7c1111eb54387/cmd/ingest/processor.go#L302)):*
<details><summary><i>Previously, cyrill-k wrote…</i></summary><blockquote>

this should probably be "... in the last column: ..."
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-12-19 08:45 UTC, cyrill-k requested changes
> Reviewed 8 of 8 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/fpki/44)* status: all files reviewed, 2 unresolved discussions / 0 of 1 LGTMs obtained / 0 of 1 approvals obtained

___
*[`cmd/ingest/processor.go` line 302 at r6](https://reviewable.io/reviews/netsec-ethz/fpki/44#-NlwVaORBb_3Vg0Mz0e_:-NlxLj7dEcFjSlL9owVu:bnnjlky) ([raw file](https://github.com/netsec-ethz/fpki/blob/94ae7ef04d6332820e64d7125de7c1111eb54387/cmd/ingest/processor.go#L302)):*
<details><summary><i>Previously, juagargi (Juan A. Garcia Pardo) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I don't believe you ;D
___
*[`pkg/mapserver/mapserver.go` line 248 at r7](https://reviewable.io/reviews/netsec-ethz/fpki/44#-NlxLsMX1VtvuZcf2mTl:-NlxLsMX1VtvuZcf2mTm:bsp3na1) ([raw file](https://github.com/netsec-ethz/fpki/blob/9475b960d2dbaf176dd7b4017cfc7cd2874d33f9/pkg/mapserver/mapserver.go#L248)):*
> ```Go
> // of all requested IDs.
> // Since each ID is 32 bytes, the hex string will always be a multiple of 64.
> func (s *MapServer) apiGetPolicyPayloads(w http.ResponseWriter, r *http.Request) {
> ```

This is one of the issues that I also fixed in my local version ;)
However, instead of splitting it into two functions (one for certs and one for policies), I made one API call that returns both certificate and policy payload objects based on their respective hashes.
I think we can merge this for now and then I'll also add my version in a later PR.


<!-- Sent from Reviewable.io -->

2023-12-19 10:20 UTC, juagargi reviewed
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/fpki/44)* status: 194 of 195 files reviewed, 2 unresolved discussions / 0 of 1 LGTMs obtained / 0 of 1 approvals obtained

___
*[`cmd/ingest/processor.go` line 302 at r6](https://reviewable.io/reviews/netsec-ethz/fpki/44#-NlwVaORBb_3Vg0Mz0e_:-Nm0_TUA37oxYa7aQqA6:b-bnand1) ([raw file](https://github.com/netsec-ethz/fpki/blob/94ae7ef04d6332820e64d7125de7c1111eb54387/cmd/ingest/processor.go#L302)):*
<details><summary><i>Previously, cyrill-k wrote…</i></summary><blockquote>

I don't believe you ;D
</blockquote></details>

Done. And committed. And pushed. :smile: now for real.
___
*[`pkg/mapserver/mapserver.go` line 248 at r7](https://reviewable.io/reviews/netsec-ethz/fpki/44#-NlxLsMX1VtvuZcf2mTl:-Nm0_ezq2yupRa01fN0g:bb73djm) ([raw file](https://github.com/netsec-ethz/fpki/blob/9475b960d2dbaf176dd7b4017cfc7cd2874d33f9/pkg/mapserver/mapserver.go#L248)):*
<details><summary><i>Previously, cyrill-k wrote…</i></summary><blockquote>

This is one of the issues that I also fixed in my local version ;)
However, instead of splitting it into two functions (one for certs and one for policies), I made one API call that returns both certificate and policy payload objects based on their respective hashes.
I think we can merge this for now and then I'll also add my version in a later PR.
</blockquote></details>

SGTM


<!-- Sent from Reviewable.io -->

2023-12-19 11:16 UTC, cyrill-k approved these changes
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/fpki/44)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @juagargi)



<!-- Sent from Reviewable.io -->

2023-12-19 13:42 UTC, merged