With juan db
netsec-ethz/fpki pull request #6
Opened 2022-05-30 21:15 UTC by XuYongzhe-ethz

Complete version of FPKI, although performance is not as good as expected. I will try to improve the performance in this week.

2022-06-01 09:10 UTC, juagargi requested changes
> Reviewed 10 of 59 files at r1.
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/fpki/6)* status: 50 of 59 files reviewed, 117 unresolved discussions / 0 of 1 LGTMs obtained / 0 of 1 approvals obtained

___
*[`pkg/mapserver/responder/responder.go` line 48 at r1](https://reviewable.io/reviews/netsec-ethz/fpki/6#-N3Pm8KNDwkY1tTEQh6z:-N3Pm8KNDwkY1tTEQh7-:bb5mp1h) ([raw file](https://github.com/netsec-ethz/fpki/blob/6016243e63f8493416cb9553cd6a0755cf0bb6d7/pkg/mapserver/responder/responder.go#L48)):*
> ```Go
> 
> // GetMapResponse: Query the proofs and materials for a list of domains. Return type: MapServerResponse
> func (mapResponder *MapResponder) GetDomainProof(ctx context.Context, domainName string) ([]common.MapServerResponse, error) {
> ```

We should have a benchmark for this function.
___
*[`pkg/mapserver/responder/responder.go` line 145 at r1](https://reviewable.io/reviews/netsec-ethz/fpki/6#-N3PmKFX7Si3ZE4nu8a2:-N3PmKFX7Si3ZE4nu8a3:b-5gg0vj) ([raw file](https://github.com/netsec-ethz/fpki/blob/6016243e63f8493416cb9553cd6a0755cf0bb6d7/pkg/mapserver/responder/responder.go#L145)):*
> ```Go
> // eg: *.google.com -> google.com
> // eg: www.google.com -> google.com
> func parseDomainName(domainName string) ([]string, error) {
> ```

also a benchmark for this one
___
*[`pkg/mapserver/trie/trie.go` line 307 at r1](https://reviewable.io/reviews/netsec-ethz/fpki/6#-N3T1yoS6cvhwQwjddPo:-N3T1yoS6cvhwQwjddPp:b7wo5yn) ([raw file](https://github.com/netsec-ethz/fpki/blob/6016243e63f8493416cb9553cd6a0755cf0bb6d7/pkg/mapserver/trie/trie.go#L307)):*
> ```Go
> 		// dont delete old nodes with atomic updated except when
> 		// moving up a shortcut, we dont record every single move
> 		s.db.updatedMux.Lock()
> ```

I'm not loving manipulating the mutexes of another structure from outside. Can we create a "method" for the `CacheDB` type that does it?
___
*[`pkg/mapserver/trie/trie.go` line 595 at r1](https://reviewable.io/reviews/netsec-ethz/fpki/6#-N3T2UB73SxheyrpSAMD:-N3T2UB73SxheyrpSAME:btlgwbf) ([raw file](https://github.com/netsec-ethz/fpki/blob/6016243e63f8493416cb9553cd6a0755cf0bb6d7/pkg/mapserver/trie/trie.go#L595)):*
> ```Go
> 		copy(node[:], h)
> 		// record new node
> 		s.db.updatedMux.Lock()
> ```

Like before, not great to interfere with the internal mutexes.
___
*[`pkg/mapserver/trie/trie_cache.go` line 74 at r1](https://reviewable.io/reviews/netsec-ethz/fpki/6#-N3T3xdA9aW5peSeku7w:-N3T3xdA9aW5peSeku7x:b-bkolgz) ([raw file](https://github.com/netsec-ethz/fpki/blob/6016243e63f8493416cb9553cd6a0755cf0bb6d7/pkg/mapserver/trie/trie_cache.go#L74)):*
> ```Go
> 
> // commitChangesToDB stores the updated nodes to disk.
> func (cacheDB *CacheDB) commitChangesToDB() error {
> ```

needs to be unit tested
___
*[`pkg/mapserver/trie/trie_cache.go` line 76 at r1](https://reviewable.io/reviews/netsec-ethz/fpki/6#-N3T3JYd4hfUh3ApA0hg:-N3T3JYd4hfUh3ApA0hh:bah6o78) ([raw file](https://github.com/netsec-ethz/fpki/blob/6016243e63f8493416cb9553cd6a0755cf0bb6d7/pkg/mapserver/trie/trie_cache.go#L76)):*
> ```Go
> func (cacheDB *CacheDB) commitChangesToDB() error {
> 	cacheDB.updatedMux.Lock()
> 	defer cacheDB.updatedMux.Unlock()
> ```

You can unlock much faster:
The `updatedMux` only locks the `updatedNodes` member, so just swap the value with a local empty slice and unlock.
___
*[`pkg/mapserver/trie/trie_cache.go` line 87 at r1](https://reviewable.io/reviews/netsec-ethz/fpki/6#-N3T4wfZAh5wsRfHkYiv:-N3T4wfZAh5wsRfHkYiw:b93yzvn) ([raw file](https://github.com/netsec-ethz/fpki/blob/6016243e63f8493416cb9553cd6a0755cf0bb6d7/pkg/mapserver/trie/trie_cache.go#L87)):*
> ```Go
> 		updates = append(updates, db.KeyValuePair{Key: hex.EncodeToString(k[:]), Value: serializeBatch(v)})
> 	}
> 	ctx, cancelF := context.WithTimeout(context.Background(), time.Minute)
> ```

This 1 minute seems somewhat arbitrary. Contexts are passed from parent function to children ones, and thus, this function should receive one.
___
*[`pkg/mapserver/trie/trie_cache.go` line 105 at r1](https://reviewable.io/reviews/netsec-ethz/fpki/6#-N3T4H4vC89JFO5e6Ksc:-N3T4H4vC89JFO5e6Ksd:b74f7si) ([raw file](https://github.com/netsec-ethz/fpki/blob/6016243e63f8493416cb9553cd6a0755cf0bb6d7/pkg/mapserver/trie/trie_cache.go#L105)):*
> ```Go
> 	}
> 
> 	if len(cacheDB.removedNode) != 0 {
> ```

`len() > 0` (more common)
___
*[`pkg/mapserver/trie/trie_cache.go` line 105 at r1](https://reviewable.io/reviews/netsec-ethz/fpki/6#-N3T4c7GDJ6C7Hwxqw6_:-N3T4c7GDJ6C7Hwxqw6a:bxyjyub) ([raw file](https://github.com/netsec-ethz/fpki/blob/6016243e63f8493416cb9553cd6a0755cf0bb6d7/pkg/mapserver/trie/trie_cache.go#L105)):*
> ```Go
> 	}
> 
> 	if len(cacheDB.removedNode) != 0 {
> ```

there is a `removedMux` that should be locked. Follow the same strategy as mentioned for the `updatedMux` above.
___
*[`pkg/mapserver/trie/trie_cache.go` line 173 at r1](https://reviewable.io/reviews/netsec-ethz/fpki/6#-N3T5MMYEfZjsDxb2VXu:-N3T5MMYEfZjsDxb2VXv:bu7hfmt) ([raw file](https://github.com/netsec-ethz/fpki/blob/6016243e63f8493416cb9553cd6a0755cf0bb6d7/pkg/mapserver/trie/trie_cache.go#L173)):*
> ```Go
> /*
> // Start: creates workers and starts the worker distributor thread,
> func (db *CacheDB) Start() {
> ```

will we use the pool style workers you have here?
___
*[`pkg/mapserver/updater/certs_updater.go` line 18 at r1](https://reviewable.io/reviews/netsec-ethz/fpki/6#-N3T6Woi7MolA5MYoxaF:-N3T6Woi7MolA5MYoxaG:bes5l9e) ([raw file](https://github.com/netsec-ethz/fpki/blob/6016243e63f8493416cb9553cd6a0755cf0bb6d7/pkg/mapserver/updater/certs_updater.go#L18)):*
> ```Go
> 
> // UpdateDomainEntriesUsingCerts: Update the domain entries using the domain certificates
> func (mapUpdator *MapUpdater) UpdateDomainEntriesUsingCerts(certs []*x509.Certificate, readerNum int) (int, error) {
> ```

add a UT
___
*[`pkg/mapserver/updater/certs_updater.go` line 79 at r1](https://reviewable.io/reviews/netsec-ethz/fpki/6#-N3T7-3c9R-2DWqS-Fdw:-N3T7-3c9R-2DWqS-Fdx:b-aqtfp8) ([raw file](https://github.com/netsec-ethz/fpki/blob/6016243e63f8493416cb9553cd6a0755cf0bb6d7/pkg/mapserver/updater/certs_updater.go#L79)):*
> ```Go
> }
> 
> func getAffectedDomainAndCertMap(certs []*x509.Certificate) (map[string]byte, map[string][]*x509.Certificate) {
> ```

docstring and UT
___
*[`pkg/mapserver/updater/certs_updater.go` line 101 at r1](https://reviewable.io/reviews/netsec-ethz/fpki/6#-N3T8DJqApwh1aZ4RN09:-N3T8DJqApwh1aZ4RN0A:b-ac7593) ([raw file](https://github.com/netsec-ethz/fpki/blob/6016243e63f8493416cb9553cd6a0755cf0bb6d7/pkg/mapserver/updater/certs_updater.go#L101)):*
> ```Go
> 			domainNameHash := hex.EncodeToString(trie.Hasher([]byte(domainName)))
> 
> 			affectedDomainsMap[domainNameHash] = 1
> ```

the signature of the function should return a set. Because there are no explicit sets in Go, the common practice is to use something like
```go
var thisIsASet map[string]struct{}
```
(a map to an empty struct)

Because this type is used very often here, I suggest you declare a new type
```go
type domainSet map[string]struct{}
```
___
*[`pkg/mapserver/updater/certs_updater.go` line 116 at r1](https://reviewable.io/reviews/netsec-ethz/fpki/6#-N3T8jIG3mLdXsY4lVB0:-N3T8jIG3mLdXsY4lVB1:bnglyxl) ([raw file](https://github.com/netsec-ethz/fpki/blob/6016243e63f8493416cb9553cd6a0755cf0bb6d7/pkg/mapserver/updater/certs_updater.go#L116)):*
> ```Go
> // 1. Subject name
> // 2. SANs
> func extractCertDomains(cert *x509.Certificate) []string {
> ```

fix docstring
___
*[`pkg/mapserver/updater/certs_updater.go` line 117 at r1](https://reviewable.io/reviews/netsec-ethz/fpki/6#-N3T8sAr5FBImUS4Jy0U:-N3T8sAr5FBImUS4Jy0V:bommhjm) ([raw file](https://github.com/netsec-ethz/fpki/blob/6016243e63f8493416cb9553cd6a0755cf0bb6d7/pkg/mapserver/updater/certs_updater.go#L117)):*
> ```Go
> // 2. SANs
> func extractCertDomains(cert *x509.Certificate) []string {
> 	domains := make(map[string]byte)
> ```

`domains := make(map[string]struct{})`
___
*[`pkg/mapserver/updater/certs_updater.go` line 118 at r1](ht [...]

2022-06-02 19:23 UTC, XuYongzhe-ethz reviewed
Sorry to apply so late
For 1: I will add more information in the REAME later, after the map server's README is done.
For 2, 3: I will do this after finish the changing of the code.
For 4: Sorry I forgot the check the file, because there is a commit that contains 1000 certificates for the testdata, and I miss the files... Really sorry for that
For 5: It's in the integration_test/mapserver 
For 6: Yeah it's done.
For 7: I added some description in the README, please have a look

> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/fpki/6#-:-N3_r1SWEqrSU47c9Yph:b-jtto2f)* status: 35 of 60 files reviewed, 117 unresolved discussions / 0 of 1 LGTMs obtained / 0 of 1 approvals obtained

___
*[`go.mod` line 5 at r1](https://reviewable.io/reviews/netsec-ethz/fpki/6#-N3O1Sbo8A_n_ZdjjF_Z:-N3PQ3daEntma9AK3dnw:b-gt64dj) ([raw file](https://github.com/netsec-ethz/fpki/blob/6016243e63f8493416cb9553cd6a0755cf0bb6d7/go.mod#L5)):*
<details><summary><i>Previously, juagargi (Juan A. Garcia Pardo) wrote…</i></summary><blockquote>

this should never be necessary: the module is declared (first line of this file) with the name `github.com/netsec-ethz/fpki`
</blockquote></details>

It seems the go will download module from fpki master branch, and local changes will not be applied (before I commit to the branch). So I just did this for the development. Anyway, I will remove it after everything is finished.
___
*[`Makefile` line 17 at r1](https://reviewable.io/reviews/netsec-ethz/fpki/6#-N3O3gqk2Mcm0yAihziF:-N3PQ_GXEYrGfmd3UVbA:b-9zven2) ([raw file](https://github.com/netsec-ethz/fpki/blob/6016243e63f8493416cb9553cd6a0755cf0bb6d7/Makefile#L17)):*
<details><summary><i>Previously, juagargi (Juan A. Garcia Pardo) wrote…</i></summary><blockquote>

maybe change the name of the rule: the `create_schema.sh` script will completely delete the `fpki` database and create a new one.
</blockquote></details>

Changed to "create_fpki_schema_replace_old"
___
*[`Makefile` line 24 at r1](https://reviewable.io/reviews/netsec-ethz/fpki/6#-N3O6nemCSIas0R8kKRO:-N3PRDI2BCUcDdb-J5nB:b-896fix) ([raw file](https://github.com/netsec-ethz/fpki/blob/6016243e63f8493416cb9553cd6a0755cf0bb6d7/Makefile#L24)):*
<details><summary><i>Previously, juagargi (Juan A. Garcia Pardo) wrote…</i></summary><blockquote>

qualify the binaries that come from the integration test with a prefix like `test_` e.g. `policylog_interaction` would become `test_policylog_interaction`. This way you can also add a rule to clean the test products.
</blockquote></details>

Done.
___
*[`Makefile` line 28 at r1](https://reviewable.io/reviews/netsec-ethz/fpki/6#-N3O4riADPCIiOBVQDwR:-N3PROj73zG0iLBTUm20:bs8pqef) ([raw file](https://github.com/netsec-ethz/fpki/blob/6016243e63f8493416cb9553cd6a0755cf0bb6d7/Makefile#L28)):*
<details><summary><i>Previously, juagargi (Juan A. Garcia Pardo) wrote…</i></summary><blockquote>

there is no `integration_tests/updater` and running `make` fails
</blockquote></details>

Done. Updater folder is removed, and it is integrated in the mapserver test, and I forget to remove the rule...
___
*[`config/top_10k_domains/domains.txt` line 1 at r1](https://reviewable.io/reviews/netsec-ethz/fpki/6#-N3O4NUm38Dm2wIfbSXY:-N3PRwzS9rR3h7SV-UYJ:bib0b3m) ([raw file](https://github.com/netsec-ethz/fpki/blob/6016243e63f8493416cb9553cd6a0755cf0bb6d7/config/top_10k_domains/domains.txt#L1)):*
<details><summary><i>Previously, juagargi (Juan A. Garcia Pardo) wrote…</i></summary><blockquote>

what is this file used for?
</blockquote></details>

This file is used to generate pseudo-RPC and pseudo-PC. Used for integration test. I generate some RPC and PC using the domain names from the list.
___
*[`pkg/db/db.go` line 8 at r1](https://reviewable.io/reviews/netsec-ethz/fpki/6#-N3ODrZOBVOOzN3Uo4m5:-N3PSQ-S8yNbhCIT45d8:b-896fix) ([raw file](https://github.com/netsec-ethz/fpki/blob/6016243e63f8493416cb9553cd6a0755cf0bb6d7/pkg/db/db.go#L8)):*
<details><summary><i>Previously, juagargi (Juan A. Garcia Pardo) wrote…</i></summary><blockquote>

this comment should go where the `TableName` is declared
</blockquote></details>

Done.
___
*[`pkg/db/db.go` line 67 at r1](https://reviewable.io/reviews/netsec-ethz/fpki/6#-N3OPd_H3rntQ38RvvmG:-N3PXcG-8OGP50yrlWUy:bcpgfvb) ([raw file](https://github.com/netsec-ethz/fpki/blob/6016243e63f8493416cb9553cd6a0755cf0bb6d7/pkg/db/db.go#L67)):*
> CountUpdates
I want to know how many records are there, and adjust the number of query based on the number of records. For example, if there are 50M records, then maybe it's not possible to fetch them in one query. So I can use multiple queries to fetch all the records, if I know the total number of records.
___
*[`pkg/db/db.go` line 70 at r1](https://reviewable.io/reviews/netsec-ethz/fpki/6#-N3OPYgj-FYgWqYRyQxP:-N3PZOst5IIDHftfDRbV:b-896fix) ([raw file](https://github.com/netsec-ethz/fpki/blob/6016243e63f8493416cb9553cd6a0755cf0bb6d7/pkg/db/db.go#L70)):*
<details><summary><i>Previously, juagargi (Juan A. Garcia Pardo) wrote…</i></summary><blockquote>

Call it `UpdateKeyValues`
</blockquote></details>

Done.
___
*[`pkg/db/db.go` line 73 at r1](https://reviewable.io/reviews/netsec-ethz/fpki/6#-N3OPV4w-zjA5PW74kLt:-N3PaAAQ6zCCIm9M3C2Y:b-896fix) ([raw file](https://github.com/netsec-ethz/fpki/blob/6016243e63f8493416cb9553cd6a0755cf0bb6d7/pkg/db/db.go#L73)):*
<details><summary><i>Previously, juagargi (Juan A. Garcia Pardo) wrote…</i></summary><blockquote>

Call it `DeleteKeyValues`
</blockquote></details>

Done.
___
*[`pkg/db/db.go` line 76 at r1](https://reviewable.io/reviews/netsec-ethz/fpki/6#-N3OPMOKAAg6lxTzgngE:-N3PaJmg1SO9xMbrTA1k:b-896fix) ([raw file](https://github.com/netsec-ethz/fpki/blob/6016243e63f8493416cb9553cd6a0755cf0bb6d7/pkg/db/db.go#L76)):*
<details><summary><i>Previously, juagargi (Juan A. Garcia Pardo) wrote…</i></summary><blockquote>

Call it `ReplaceKeys`
</blockquote></details>

Done.
___
*[`pkg/db/db.go` line 82 at r1](https://reviewable.io/reviews/netsec-ethz/fpki/6#-N3OP0PD3FSMHTV7xhvX:-N3PaKSWEoPf6tcXLBv6:bxga992) ([raw file](https://github.com/netsec-ethz/fpki/blob/6016243e63f8493416cb9553cd6a0755cf0bb6d7/pkg/db/db.go#L82)):*
<details><summary><i>Previously, juagargi (Juan A. Garcia Pardo) wrote…</i></summary><blockquote>

After the DB investigation, I have seen that disabling keys and re-enabling them later is of slower performance than leaving them in place (when working with several threads).
The reason is related to multi-threading.
</blockquote></details>

Removed functions
___
*[`.cer` line 1 at r1](https://reviewable.io/reviews/netsec-ethz/fpki/6#-N3OVHOm5Yf0s0xEyNWE:-N3PQ0Hq8VjHRuSA5PWh:b-896fix) ([raw file](https://github.com/netsec-ethz/fpki/blob/6016243e63f8493416cb9553cd6a0755cf0bb6d7/.cer#L1)):*
<details><summary><i>Previously, juagargi (Juan A. Garcia Pardo) wrote…</i></summary><blockquote>

remove this file
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-06-04 14:44 UTC, XuYongzhe-ethz reviewed
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/fpki/6)* status: 21 of 82 files reviewed, 111 unresolved discussions / 0 of 1 LGTMs obtained / 0 of 1 approvals obtained

___
*[`pkg/db/write.go` line 28 at r1](https://reviewable.io/reviews/netsec-ethz/fpki/6#-N3PEI8Q-zyo4prKChNs:-N3jA6Wy-F-2Rf15WzB4:b-896fix) ([raw file](https://github.com/netsec-ethz/fpki/blob/6016243e63f8493416cb9553cd6a0755cf0bb6d7/pkg/db/write.go#L28)):*
<details><summary><i>Previously, juagargi (Juan A. Garcia Pardo) wrote…</i></summary><blockquote>

This sort of counter is a bit atypical. This is more standard:
```go
for i := 0; i < dataLen/1000; i++ {
```
</blockquote></details>

Done.
___
*[`pkg/db/write.go` line 44 at r1](https://reviewable.io/reviews/netsec-ethz/fpki/6#-N3PE_PvBe1vJGli9sF1:-N3jA5EE2MEoKrG7owoZ:b-896fix) ([raw file](https://github.com/netsec-ethz/fpki/blob/6016243e63f8493416cb9553cd6a0755cf0bb6d7/pkg/db/write.go#L44)):*
<details><summary><i>Previously, juagargi (Juan A. Garcia Pardo) wrote…</i></summary><blockquote>

and do the remaining here (with `%`).
Also put in common both parts of the update. The only difference is the statement being run.
</blockquote></details>

Done.
___
*[`pkg/db/write.go` line 74 at r1](https://reviewable.io/reviews/netsec-ethz/fpki/6#-N3PG6Y14vPXgNzMZcvE:-N3jA4ep5s88rQU_e9oj:b-896fix) ([raw file](https://github.com/netsec-ethz/fpki/blob/6016243e63f8493416cb9553cd6a0755cf0bb6d7/pkg/db/write.go#L74)):*
<details><summary><i>Previously, juagargi (Juan A. Garcia Pardo) wrote…</i></summary><blockquote>

same as the loop above
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-06-05 16:54 UTC, XuYongzhe-ethz reviewed
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/fpki/6)* status: 21 of 91 files reviewed, 110 unresolved discussions / 0 of 1 LGTMs obtained / 0 of 1 approvals obtained

___
*[`pkg/db/db.go` line 61 at r1](https://reviewable.io/reviews/netsec-ethz/fpki/6#-N3ONKoz4p9neIJgIigu:-N3o_qM8Ca-w8cWZCA_h:b-896fix) ([raw file](https://github.com/netsec-ethz/fpki/blob/6016243e63f8493416cb9553cd6a0755cf0bb6d7/pkg/db/db.go#L61)):*
<details><summary><i>Previously, juagargi (Juan A. Garcia Pardo) wrote…</i></summary><blockquote>

In general, all routines should be re-entrant. That is, all routines should work fine if called from several threads, several times.
The concurrency model for the `Conn` type might not be clear:
- The `Conn` is created. Maybe several `Conn`s are created.
- Every `Conn` maintains a proper DB connection to the database.
- Methods of `Conn` are invoked from different threads (go routines)
- The `Conn` is `Close`d

This allows the caller to create as many `Conn` as they consider, and to use it from as many threads as they want.
</blockquote></details>

Done.
___
*[`pkg/mapserver/trie/trie.go` line 307 at r1](https://reviewable.io/reviews/netsec-ethz/fpki/6#-N3T1yoS6cvhwQwjddPo:-N3ofTp_3vqAIApJmn-O:b-896fix) ([raw file](https://github.com/netsec-ethz/fpki/blob/6016243e63f8493416cb9553cd6a0755cf0bb6d7/pkg/mapserver/trie/trie.go#L307)):*
<details><summary><i>Previously, juagargi (Juan A. Garcia Pardo) wrote…</i></summary><blockquote>

I'm not loving manipulating the mutexes of another structure from outside. Can we create a "method" for the `CacheDB` type that does it?
</blockquote></details>

Done.
___
*[`pkg/mapserver/trie/trie.go` line 595 at r1](https://reviewable.io/reviews/netsec-ethz/fpki/6#-N3T2UB73SxheyrpSAMD:-N3ofUaz8qNGA20aH7hx:b-896fix) ([raw file](https://github.com/netsec-ethz/fpki/blob/6016243e63f8493416cb9553cd6a0755cf0bb6d7/pkg/mapserver/trie/trie.go#L595)):*
<details><summary><i>Previously, juagargi (Juan A. Garcia Pardo) wrote…</i></summary><blockquote>

Like before, not great to interfere with the internal mutexes.
</blockquote></details>

Done.
___
*[`pkg/mapserver/trie/trie_cache.go` line 76 at r1](https://reviewable.io/reviews/netsec-ethz/fpki/6#-N3T3JYd4hfUh3ApA0hg:-N3ofl6K4vEvfiCqhSLh:bb6un1j) ([raw file](https://github.com/netsec-ethz/fpki/blob/6016243e63f8493416cb9553cd6a0755cf0bb6d7/pkg/mapserver/trie/trie_cache.go#L76)):*
<details><summary><i>Previously, juagargi (Juan A. Garcia Pardo) wrote…</i></summary><blockquote>

You can unlock much faster:
The `updatedMux` only locks the `updatedNodes` member, so just swap the value with a local empty slice and unlock.
</blockquote></details>

Done
___
*[`pkg/mapserver/trie/trie_cache.go` line 87 at r1](https://reviewable.io/reviews/netsec-ethz/fpki/6#-N3T4wfZAh5wsRfHkYiv:-N3olX0c8uM_tbBfRJUV:b-896fix) ([raw file](https://github.com/netsec-ethz/fpki/blob/6016243e63f8493416cb9553cd6a0755cf0bb6d7/pkg/mapserver/trie/trie_cache.go#L87)):*
<details><summary><i>Previously, juagargi (Juan A. Garcia Pardo) wrote…</i></summary><blockquote>

This 1 minute seems somewhat arbitrary. Contexts are passed from parent function to children ones, and thus, this function should receive one.
</blockquote></details>

Done.
___
*[`pkg/mapserver/trie/trie_cache.go` line 105 at r1](https://reviewable.io/reviews/netsec-ethz/fpki/6#-N3T4c7GDJ6C7Hwxqw6_:-N3omBox1CZrmRDsCt_u:b-896fix) ([raw file](https://github.com/netsec-ethz/fpki/blob/6016243e63f8493416cb9553cd6a0755cf0bb6d7/pkg/mapserver/trie/trie_cache.go#L105)):*
<details><summary><i>Previously, juagargi (Juan A. Garcia Pardo) wrote…</i></summary><blockquote>

there is a `removedMux` that should be locked. Follow the same strategy as mentioned for the `updatedMux` above.
</blockquote></details>

Done.



_Code quote:_
```Go
for k := range cacheDB.removedNode {
```


<!-- Sent from Reviewable.io -->

2022-06-05 19:00 UTC, XuYongzhe-ethz reviewed
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/fpki/6)* status: 21 of 91 files reviewed, 110 unresolved discussions / 0 of 1 LGTMs obtained / 0 of 1 approvals obtained

___
*[`pkg/mapserver/updater/dbutil.go` line 20 at r1](https://reviewable.io/reviews/netsec-ethz/fpki/6#-N3TVwrVAqd8UedONs0K:-N3pEOUN9MLY_WighXJF:b-896fix) ([raw file](https://github.com/netsec-ethz/fpki/blob/6016243e63f8493416cb9553cd6a0755cf0bb6d7/pkg/mapserver/updater/dbutil.go#L20)):*
<details><summary><i>Previously, juagargi (Juan A. Garcia Pardo) wrote…</i></summary><blockquote>

contexts should be passed from parent to children, not created like this
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-06-07 15:07 UTC, XuYongzhe-ethz reviewed
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/fpki/6)* status: 21 of 93 files reviewed, 110 unresolved discussions / 0 of 1 LGTMs obtained / 0 of 1 approvals obtained

___
*[`pkg/mapserver/logpicker/logpicker.go` line 39 at r1](https://reviewable.io/reviews/netsec-ethz/fpki/6#-N3PASTRE_I2MGF4l43b:-N3ygGDX-arDAvKSc_NT:b-896fix) ([raw file](https://github.com/netsec-ethz/fpki/blob/6016243e63f8493416cb9553cd6a0755cf0bb6d7/pkg/mapserver/logpicker/logpicker.go#L39)):*
<details><summary><i>Previously, juagargi (Juan A. Garcia Pardo) wrote…</i></summary><blockquote>

change doc string
</blockquote></details>

Done.
___
*[`tools/create_schema.sh` line 102 at r1](https://reviewable.io/reviews/netsec-ethz/fpki/6#-N3O2jnA6DxfENJq50Gf:-N3yh-qU19o5T4ZzCfcv:b-3cvo9c) ([raw file](https://github.com/netsec-ethz/fpki/blob/6016243e63f8493416cb9553cd6a0755cf0bb6d7/tools/create_schema.sh#L102)):*
<details><summary><i>Previously, juagargi (Juan A. Garcia Pardo) wrote…</i></summary><blockquote>

Why `VARCHAR(64)` ?
It should be `VARBINARY(33)` because Mysql is able to work with bytes and in a much faster fashion.
</blockquote></details>

Done, chawed to VarBinary(32)
___
*[`pkg/mapserver/domain/domain.go` line 68 at r1](https://reviewable.io/reviews/netsec-ethz/fpki/6#-N3OY6zf26IaT-Pa0uiR:-N3yaBX-3eAECATnlGE1:bxbanne) ([raw file](https://github.com/netsec-ethz/fpki/blob/6016243e63f8493416cb9553cd6a0755cf0bb6d7/pkg/mapserver/domain/domain.go#L68)):*
<details><summary><i>Previously, juagargi (Juan A. Garcia Pardo) wrote…</i></summary><blockquote>

you can skip the first iteration
</blockquote></details>

Moved to pkg/domain
___
*[`pkg/mapserver/domain/domain.go` line 71 at r1](https://reviewable.io/reviews/netsec-ethz/fpki/6#-N3OYIdEERHFWaSkY7r3:-N3yaCNc0pGsBRBTyKvP:bxbanne) ([raw file](https://github.com/netsec-ethz/fpki/blob/6016243e63f8493416cb9553cd6a0755cf0bb6d7/pkg/mapserver/domain/domain.go#L71)):*
<details><summary><i>Previously, juagargi (Juan A. Garcia Pardo) wrote…</i></summary><blockquote>

return result here directly. Remove `main_loop` label.
</blockquote></details>

Moved to pkg/domain
___
*[`pkg/mapserver/domain/domain.go` line 81 at r1](https://reviewable.io/reviews/netsec-ethz/fpki/6#-N3OXK_Y9_-oGw3mx-Md:-N3ya4rfCJDdJ2YpTLRz:bxbanne) ([raw file](https://github.com/netsec-ethz/fpki/blob/6016243e63f8493416cb9553cd6a0755cf0bb6d7/pkg/mapserver/domain/domain.go#L81)):*
<details><summary><i>Previously, juagargi (Juan A. Garcia Pardo) wrote…</i></summary><blockquote>

Add a UT for this.
</blockquote></details>

Moved to pkg/domain
___
*[`pkg/mapserver/domain/domain.go` line 83 at r1](https://reviewable.io/reviews/netsec-ethz/fpki/6#-N3OXgMYBBTODiq8TiSd:-N3ya5ZY1umUdZsJsG9b:bxbanne) ([raw file](https://github.com/netsec-ethz/fpki/blob/6016243e63f8493416cb9553cd6a0755cf0bb6d7/pkg/mapserver/domain/domain.go#L83)):*
<details><summary><i>Previously, juagargi (Juan A. Garcia Pardo) wrote…</i></summary><blockquote>

skip the first iteration
</blockquote></details>

Moved to pkg/domain
___
*[`pkg/mapserver/domain/domain.go` line 92 at r1](https://reviewable.io/reviews/netsec-ethz/fpki/6#-N3OWNzt45wlfA08iEKB:-N3ya35V2dTuIFRcV2Zy:bxbanne) ([raw file](https://github.com/netsec-ethz/fpki/blob/6016243e63f8493416cb9553cd6a0755cf0bb6d7/pkg/mapserver/domain/domain.go#L92)):*
<details><summary><i>Previously, juagargi (Juan A. Garcia Pardo) wrote…</i></summary><blockquote>

Add a UT for this function.
</blockquote></details>

Moved to pkg/domain
___
*[`pkg/mapserver/domain/domain.go` line 128 at r1](https://reviewable.io/reviews/netsec-ethz/fpki/6#-N3OW3Hg9J3VXluLNFUV:-N3y_yWaEi6VOtFS-RPF:bxbanne) ([raw file](https://github.com/netsec-ethz/fpki/blob/6016243e63f8493416cb9553cd6a0755cf0bb6d7/pkg/mapserver/domain/domain.go#L128)):*
<details><summary><i>Previously, juagargi (Juan A. Garcia Pardo) wrote…</i></summary><blockquote>

Add a UT for the function.
</blockquote></details>

Moved to pkg/domain
___
*[`pkg/mapserver/domain/domain_test.go` line 13 at r1](https://reviewable.io/reviews/netsec-ethz/fpki/6#-N3OZHBx8V13sXn2PvRJ:-N3yg75h5iLh1w7AHRGM:bb6un1j) ([raw file](https://github.com/netsec-ethz/fpki/blob/6016243e63f8493416cb9553cd6a0755cf0bb6d7/pkg/mapserver/domain/domain_test.go#L13)):*
<details><summary><i>Previously, juagargi (Juan A. Garcia Pardo) wrote…</i></summary><blockquote>

convert to test cases.
There is (used to be) an example at https://github.com/netsec-ethz/fpki/blob/master/pkg/db/implicit_repr_test.go#L14

</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2022-06-11 20:31 UTC, XuYongzhe-ethz reviewed
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/fpki/6)* status: 33 of 107 files reviewed, 77 unresolved discussions / 0 of 1 LGTMs obtained / 0 of 1 approvals obtained

___
*[`config/top_10k_domains/domains.txt` line 1 at r1](https://reviewable.io/reviews/netsec-ethz/fpki/6#-N3O4NUm38Dm2wIfbSXY:-N4Ddf1RCVXQr00L83PJ:b-j7pcxq) ([raw file](https://github.com/netsec-ethz/fpki/blob/6016243e63f8493416cb9553cd6a0755cf0bb6d7/config/top_10k_domains/domains.txt#L1)):*
<details><summary><i>Previously, juagargi (Juan A. Garcia Pardo) wrote…</i></summary><blockquote>

I see there are two `domains.txt` files, but only one is used in the code:
```
$ git ls-files '*domains.txt*'
config/top_10k_domains/domains.txt
pkg/mapserver/updater/testdata/domain_list/domains.txt

$ git grep -n domains.txt
pkg/mapserver/updater/updater_test.go:23:       pcList, rpcList, err := logpicker.GetPCAndRPC("./testdata/domain_list/domains.txt", 0, 0, 0)
pkg/mapserver/updater/updater_test.go:265:      pcList, rpcList, err := logpicker.GetPCAndRPC("./testdata/domain_list/domains.txt", 0, 0, 0)
```
</blockquote></details>

One for unit test, and the other for benchmark.
The unit test is not optimised. The checking is an iteration over a list(check the whole list on every domain). So if the size of domains is large, the unit tests will takes a lot of time. So the domains.txt in the unit test only contains 1000 domains, and the benchmark list contains 10,000 domains.
___
*[`pkg/mapserver/trie/trie_cache.go` line 53 at r57](https://reviewable.io/reviews/netsec-ethz/fpki/6#-N4BvDzU9UM1Po9cw3OK:-N4DhOkm62BtW5WMo9LI:b-896fix) ([raw file](https://github.com/netsec-ethz/fpki/blob/2f10fc676d66a16d7aaf56dd9034f449d8c1b727/pkg/mapserver/trie/trie_cache.go#L53)):*
<details><summary><i>Previously, juagargi (Juan A. Garcia Pardo) wrote…</i></summary><blockquote>

rename to something more relevant, e.g. `toDelete` 
</blockquote></details>

Done.



_Code quote:_
```Go
	keys := []common.SHA256Output{}
```
___
*[`pkg/mapserver/trie/trie_cache.go` line 65 at r57](https://reviewable.io/reviews/netsec-ethz/fpki/6#-N4Buy_Y5ag4O2SZiHm6:-N4DhZbU9K50B_wbYa8K:b-896fix) ([raw file](https://github.com/netsec-ethz/fpki/blob/2f10fc676d66a16d7aaf56dd9034f449d8c1b727/pkg/mapserver/trie/trie_cache.go#L65)):*
<details><summary><i>Previously, juagargi (Juan A. Garcia Pardo) wrote…</i></summary><blockquote>

no need for the `if` condition
</blockquote></details>

Done.



_Code quote:_
```Go
if len(cacheDB.removedNode) > 0 {
```
___
*[`pkg/mapserver/updater/certs_updater.go` line 18 at r1](https://reviewable.io/reviews/netsec-ethz/fpki/6#-N3T6Woi7MolA5MYoxaF:-N4E45vh8wRlk9XeG81b:bxanrej) ([raw file](https://github.com/netsec-ethz/fpki/blob/6016243e63f8493416cb9553cd6a0755cf0bb6d7/pkg/mapserver/updater/certs_updater.go#L18)):*
<details><summary><i>Previously, juagargi (Juan A. Garcia Pardo) wrote…</i></summary><blockquote>

add a UT
</blockquote></details>

Done. I split the large function into some small function, and test the small functions(without db connections).
___
*[`pkg/mapserver/updater/certs_updater.go` line 79 at r1](https://reviewable.io/reviews/netsec-ethz/fpki/6#-N3T7-3c9R-2DWqS-Fdw:-N4E4UJA1Sey4z_BElSQ:b-896fix) ([raw file](https://github.com/netsec-ethz/fpki/blob/6016243e63f8493416cb9553cd6a0755cf0bb6d7/pkg/mapserver/updater/certs_updater.go#L79)):*
<details><summary><i>Previously, juagargi (Juan A. Garcia Pardo) wrote…</i></summary><blockquote>

docstring and UT
</blockquote></details>

Done.
___
*[`pkg/mapserver/updater/certs_updater.go` line 101 at r1](https://reviewable.io/reviews/netsec-ethz/fpki/6#-N3T8DJqApwh1aZ4RN09:-N4E6hdgEa_ceGe9WsHL:b-896fix) ([raw file](https://github.com/netsec-ethz/fpki/blob/6016243e63f8493416cb9553cd6a0755cf0bb6d7/pkg/mapserver/updater/certs_updater.go#L101)):*
<details><summary><i>Previously, juagargi (Juan A. Garcia Pardo) wrote…</i></summary><blockquote>

the signature of the function should return a set. Because there are no explicit sets in Go, the common practice is to use something like
```go
var thisIsASet map[string]struct{}
```
(a map to an empty struct)

Because this type is used very often here, I suggest you declare a new type
```go
type domainSet map[string]struct{}
```
</blockquote></details>

Done.
___
*[`pkg/mapserver/updater/certs_updater.go` line 116 at r1](https://reviewable.io/reviews/netsec-ethz/fpki/6#-N3T8jIG3mLdXsY4lVB0:-N4E4saS7ileLJXGHJyD:bs7wumx) ([raw file](https://github.com/netsec-ethz/fpki/blob/6016243e63f8493416cb9553cd6a0755cf0bb6d7/pkg/mapserver/updater/certs_updater.go#L116)):*
<details><summary><i>Previously, juagargi (Juan A. Garcia Pardo) wrote…</i></summary><blockquote>

fix docstring
</blockquote></details>

Done. 
___
*[`pkg/mapserver/updater/certs_updater.go` line 117 at r1](https://reviewable.io/reviews/netsec-ethz/fpki/6#-N3T8sAr5FBImUS4Jy0U:-N4E6j7g2n16XzpdKh2_:b-896fix) ([raw file](https://github.com/netsec-ethz/fpki/blob/6016243e63f8493416cb9553cd6a0755cf0bb6d7/pkg/mapserver/updater/certs_updater.go#L117)):*
<details><summary><i>Previously, juagargi (Juan A. Garcia Pardo) wrote…</i></summary><blockquote>

`domains := make(map[string]struct{})`
</blockquote></details>

Done.
___
*[`pkg/mapserver/updater/certs_updater.go` line 123 at r1](https://reviewable.io/reviews/netsec-ethz/fpki/6#-N3T946bEj153Qyx4H2n:-N4EDdP6-gArtKi4DUgP:b-896fix) ([raw file](https://github.com/netsec-ethz/fpki/blob/6016243e63f8493416cb9553cd6a0755cf0bb6d7/pkg/mapserver/updater/certs_updater.go#L123)):*
<details><summary><i>Previously, juagargi (Juan A. Garcia Pardo) wrote…</i></summary><blockquote>

`domains[cert.Subject.CommonName] = struct{}{}`
</blockquote></details>

Done.
___
*[`pkg/mapserver/updater/certs_updater.go` line 135 at r1](https://reviewable.io/reviews/netsec-ethz/fpki/6#-N3T9fEc2KB5XuuMOvj0:-N4EDkOA6-OBvnMbwZ57:b-896fix) ([raw file](https://github.com/netsec-ethz/fpki/blob/6016243e63f8493416cb9553cd6a0755cf0bb6d7/pkg/mapserver/updater/certs_updater.go#L135)):*
<details><summary><i>Previously, juagargi (Juan A. Garcia Pardo) wrote…</i></summary><blockquote>

fix docstring
</blockquote></details>

Done.



_Code quote:_
```Go
domainEntries map[common.SHA256Output]*mapCommon.DomainEntry,
```
___
*[`pkg/mapserver/updater/certs_updater.go` line 136 at r1](https://reviewable.io/reviews/netsec-ethz/fpki/6#-N3T9mTo0EP1AMze2xfM:-N4EDlA6-ZAiRD4WTuFX:b-896fix) ([raw file](https://github.com/netsec-ethz/fpki/blob/6016243e63f8493416cb9553cd6a0755cf0bb6d7/pkg/mapserver/updater/certs_updater.go#L136)):*
<details><summary><i>Previously, juagargi (Juan A. Garcia Pardo) wrote…</i></summary><blockquote>

make this a "set"
</blockquote></details>

Done.
___
*[`pkg/mapserver/updater/certs_updater.go` line 147 at r1](https://reviewable.io/reviews/netsec-ethz/fpki/6#-N3TAGO49dL26UM-BK5M:-N4EG26T3Ngm21SBLMZ2:b-896fix) ([raw file](https://github.com/netsec-ethz/fpki/blob/6016243e63f8493416cb9553cd6a0755cf0bb6d7/pkg/mapserver/updater/certs_updater.go#L147)):*
<details><summary><i>Previously, juagargi (Juan A. Garcia Pardo) wrote…</i></summary><blockquote>

instead do something like this:
```go
if !ok {
	domainEntry = &common.DomainEntry{DomainName: domainName}
	domainEntries[domainNameHash] = domainEntry
}
```
</blockquote></details>

Done.
___
*[`pkg/mapserver/updater/certs_updater.go` line 182 at r1](https://reviewable.io/reviews/netsec-ethz/fpki/6#-N3TAZT4-kSF0dqWMt3D:-N4EG5wC88s80uLkcddp:b-896fix) ([raw file](https://github.com/netsec-ethz/fpki/blob/6016243e63f8493416cb9553cd6a0755cf0bb6d7/pkg/mapserver/updater/certs_updater.go#L182)):*
<details><summary><i>Previously, juagargi (Juan A. Garcia Pardo) wrote…</i></summary><blockquote>

fix docstring
add UT
</blockquote></details>

Done.
___
*[`pkg/mapserver/updater/certs_updater.go` line 185 at r1](https://reviewable.io/reviews/netsec-ethz/fpki/6#-N3TBJ0w4gFI_t0Cyxzo:-N4EJnlIET3zC2kJ02ai:b-896fix) ([raw file](https://github.com/netsec-ethz/fpki/blob/6016243e63f8493416cb9553cd6a0755cf0bb6d7/pkg/mapserve [...]

2022-06-12 17:41 UTC, XuYongzhe-ethz reviewed
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/fpki/6)* status: 33 of 109 files reviewed, 77 unresolved discussions / 0 of 1 LGTMs obtained / 0 of 1 approvals obtained

___
*[`pkg/mapserver/responder/responder.go` line 145 at r1](https://reviewable.io/reviews/netsec-ethz/fpki/6#-N3PmKFX7Si3ZE4nu8a2:-N4NmP9dBfqm_kiWBaGn:bvspc1m) ([raw file](https://github.com/netsec-ethz/fpki/blob/6016243e63f8493416cb9553cd6a0755cf0bb6d7/pkg/mapserver/responder/responder.go#L145)):*
> It's integrated in the benchmark folder
___
*[`pkg/mapserver/updater/rpc_updater.go` line 190 at r1](https://reviewable.io/reviews/netsec-ethz/fpki/6#-N3TUImL-oBfiNqj2StX:-N4NmVMU5ozYR2zmUnls:bb6un1j) ([raw file](https://github.com/netsec-ethz/fpki/blob/6016243e63f8493416cb9553cd6a0755cf0bb6d7/pkg/mapserver/updater/rpc_updater.go#L190)):*
<details><summary><i>Previously, juagargi (Juan A. Garcia Pardo) wrote…</i></summary><blockquote>

This function seems very similar to a previous one. Can their code be put more in common?
</blockquote></details>

Done
___
*[`pkg/mapserver/updater/updater.go` line 187 at r1](https://reviewable.io/reviews/netsec-ethz/fpki/6#-N3TK0GM4T3Jzsird6gh:-N4NobR9E8TYfn-20qoQ:b-896fix) ([raw file](https://github.com/netsec-ethz/fpki/blob/6016243e63f8493416cb9553cd6a0755cf0bb6d7/pkg/mapserver/updater/updater.go#L187)):*
<details><summary><i>Previously, juagargi (Juan A. Garcia Pardo) wrote…</i></summary><blockquote>

set the capacity to `len(updateInput)`
</blockquote></details>

Done.



_Code quote:_
```Go
keyResult := [][]byte{}
```
___
*[`pkg/mapserver/updater/updater.go` line 188 at r1](https://reviewable.io/reviews/netsec-ethz/fpki/6#-N3TK5UiDFZtcGS9bsWk:-N4NobzK5ipPBO1ynQGF:b-896fix) ([raw file](https://github.com/netsec-ethz/fpki/blob/6016243e63f8493416cb9553cd6a0755cf0bb6d7/pkg/mapserver/updater/updater.go#L188)):*
<details><summary><i>Previously, juagargi (Juan A. Garcia Pardo) wrote…</i></summary><blockquote>

same as above
</blockquote></details>

Done.
___
*[`scripts/integration_tests.sh` line 20 at r1](https://reviewable.io/reviews/netsec-ethz/fpki/6#-N3O6bqh3aDfDobEe6xH:-N4NznsV07dHgLabj9w6:b-896fix) ([raw file](https://github.com/netsec-ethz/fpki/blob/6016243e63f8493416cb9553cd6a0755cf0bb6d7/scripts/integration_tests.sh#L20)):*
<details><summary><i>Previously, juagargi (Juan A. Garcia Pardo) wrote…</i></summary><blockquote>

don't you need to create the schema first?
</blockquote></details>

Done.
___
*[`scripts/integration_tests.sh` line 25 at r1](https://reviewable.io/reviews/netsec-ethz/fpki/6#-N3O60eB-prmwdshPzIj:-N4NzmYRBczVABNL3C9d:b-896fix) ([raw file](https://github.com/netsec-ethz/fpki/blob/6016243e63f8493416cb9553cd6a0755cf0bb6d7/scripts/integration_tests.sh#L25)):*
<details><summary><i>Previously, juagargi (Juan A. Garcia Pardo) wrote…</i></summary><blockquote>

this script exits with 0 even in the case of failure
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-06-14 16:00 UTC, juagargi requested changes
> Reviewed 1 of 14 files at r50, 1 of 19 files at r71.
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/fpki/6)* status: 33 of 110 files reviewed, 59 unresolved discussions / 0 of 1 LGTMs obtained / 0 of 1 approvals obtained

___
*[`config/top_10k_domains/domains.txt` line 1 at r1](https://reviewable.io/reviews/netsec-ethz/fpki/6#-N3O4NUm38Dm2wIfbSXY:-N4XVN2t2NHQ9uu4fqqe:b-gdqdax) ([raw file](https://github.com/netsec-ethz/fpki/blob/6016243e63f8493416cb9553cd6a0755cf0bb6d7/config/top_10k_domains/domains.txt#L1)):*
<details><summary><i>Previously, XuYongzhe-ethz wrote…</i></summary><blockquote>

One for unit test, and the other for benchmark.
The unit test is not optimised. The checking is an iteration over a list(check the whole list on every domain). So if the size of domains is large, the unit tests will takes a lot of time. So the domains.txt in the unit test only contains 1000 domains, and the benchmark list contains 10,000 domains.
</blockquote></details>

Okay. Which files are using `pkg/mapserver/updater/testdata/domain_list/domains.txt` and which files are using `config/top_10k_domains/domains.txt`?
___
*[`pkg/db/db.go` line 41 at r1](https://reviewable.io/reviews/netsec-ethz/fpki/6#-N3OCSwA1ZMw9cjnAs5o:-N4Xnfh-AG8Ga66nRADk:bynbr4t) ([raw file](https://github.com/netsec-ethz/fpki/blob/6016243e63f8493416cb9553cd6a0755cf0bb6d7/pkg/db/db.go#L41)):*
<details><summary><i>Previously, XuYongzhe-ethz wrote…</i></summary><blockquote>

Do you mean changing structure "KeyValuePair" to "Tree"? 
</blockquote></details>

I meant this
```go
const (
	DomainEntries tableName = iota
	Tree
	Updates
)
```
I'm changing this right now.


<!-- Sent from Reviewable.io -->

2022-06-21 09:31 UTC, juagargi approved these changes
Let's merge this for now, and solve the remaining problems via issues in Github.

> Reviewed 1 of 14 files at r2, 1 of 14 files at r87.
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/fpki/6#-:-N54aAEdCYLgD93qXMZm:b19lu1e)* status: 33 of 119 files reviewed, 10 unresolved discussions / 0 of 1 LGTMs obtained / 0 of 1 approvals obtained



<!-- Sent from Reviewable.io -->

2022-06-21 09:33 UTC, merged